NEWS.txt, src/Dialogs/Device/DeviceEditWidget.cpp
Additional TCP Port 2000 to use RS232 to WLAN adapters with Port 2000 (for e.g. custom "iGlide"-WLAN-Modul, or Air-Connect with disabled password)
=>  Additional TCP Port 2000

src/Form/DigitEntry.cpp
Using auto, degrees is created as an int, causing entered coordinates' fractional parts to be ignored (i.e., causing latitude and longitude to be in integer degrees).
To run unit testing for this, use "make debug" and then run RunGeoPointEntry.
=> src/Form: change degrees from auto to double

test/src/TestFlatLine.cpp
These test cases demonstrate a problem with FlatLine::IntersectOriginCircle when dx<0 for the line. The calculated X values get reversed: x1, y2 and x2, y1 instead of x1, y1 and x2, y2. I'll send the fix for the problem separately, making it easier to test before and after the fix.
=> test/src: add test cases to show problem with dx<0 line

test/data/waypoints2.cup, test/src/TestWaypointReader.cpp
Some CUP files (e.g., those saved/created by SeeYou Mobile) contain a runway width (rwwidth) field. This added testing demonstrates failures with such a file with the current code but demonstrates success with the pull request I submitted for a fix (PR #56).
=> test/src: add testing for CUP file with runway width field

build/ct-ng/armv7a-a8neon-linux-musleabihf.config, build/kobo.mk, build/python/build/autotools.py, build/python/build/curl.py, build/python/build/libpng.py, build/python/build/libs.py, build/python/build/libstdcxxmuslheaders.py, build/python/build/lua.py, build/python/build/makeproject.py, build/python/build/openssl.py, build/python/build/sdl2.py, build/python/build/zlib.py, build/targets.mk, build/thirdparty.mk, build/thirdparty.py, lib/musl/patches/arm_atomics_recent_binutils.patch, lib/musl/patches/musl-1.1.16-__sprintf_chk.patch, lib/musl/patches/series, lib/salsa-lib/patches/correct_poll_h.diff, lib/salsa-lib/patches/series, src/Math/Trig.hpp, src/Net/IPv4Address.cxx, src/Net/IPv4Address.hxx, src/Thread/Name.hpp, src/Thread/Thread.cpp, src/Topography/shapelib/mapserver-config.h, src/zzip/_config.h
Add musl libc support, and use it instead of glibc for the KOBO target.
Advantages:
* very lightweight
* can be statically linked
* support for old Linux kernels
Uploaded my build of the toolchain here: http://s15356785.onlinehome-server.info/~felix/arm-unknown-linux-musleabihf-2017-09-17.tar.gz
sha256sum: ca2a4d104aacf364612f55353cfc16b1868722fa6eab2ecf11b2b35e917e430f
Built with ct-ng with the configuration "build/ct-ng/arm-unknown-linux-musleabihf.config" (see commit f7129dc).
=> musl libc (for Kobo)

.gitmodules
Backport of https://github.com/XCSoar/XCSoar/pull/65 to the `v6.8.x` branch.
see #64
=> Adjust URL for `android/ioio` submodule

.circleci/config.yml, build/libboost.mk
This is a forward port of https://github.com/XCSoar/XCSoar/pull/59 to the `master` branch
=> Add basic CircleCI instructions (for `master` branch)

android/src/SoundUtil.java, src/Android/SoundUtil.cpp, src/Android/SoundUtil.hpp, src/Audio/Sound.cpp
This brings SoundUtil functionality on Android on par with WIN32. If the name of the resource to be played ends with .wav it will be loaded as an external file and played. A quick way to test it is with a simple init.lua file:
```lua
xcsoar.fire_legacy_event("PlaySound", "test.wav")
```
=> [Android] Make it possible to play external wav files

src/Dialogs/DownloadFilePicker.cpp
When the repository is cached locally  DownloadFilePickerWidget::RefreshList is called twice on initial load - once
for the local cache and then again when the repository download finishes. Since RefreshList() is not idempotent this results
in repository items to be added twice to the items vector. This change prevents that by clearing the items vector each time.
Fixes https://github.com/XCSoar/XCSoar/issues/108
=> prevent DownloadFilePicker options from being listed twice

src/Dialogs/DownloadFilePicker.cpp
When the repository is cached locally  DownloadFilePickerWidget::RefreshList is called twice on initial load - once
for the local cache and then again when the repository download finishes. Since RefreshList() is not idempotent this results
in repository items to be added twice to the items vector. This change prevents that by clearing the items vector each time.
Fixes https://github.com/XCSoar/XCSoar/issues/108
=> [6.8] prevent DownloadFilePicker options from being listed twice

NEWS.txt, src/Dialogs/Settings/Panels/SiteConfigPanel.cpp, src/FLARM/Glue.cpp, src/FLARM/Glue.hpp, src/Profile/ProfileKeys.cpp, src/Profile/ProfileKeys.hpp, src/UtilsSettings.cpp, src/UtilsSettings.hpp
We're using [SoftRF](https://github.com/lyusupov/SoftRF) devices in our aeroclub. These devices provide information about OGN devices in the vicinity of the aircraft as a FLARM source. This change makes it possible to pick a FLARM/OGN device database in the System Configuration --> Site Files. Optionally, a fresh FLARMNET/OGN device database can be download using the [XCSoar data repository](https://github.com/XCSoar/xcsoar-data-repository). The related data repository PR is: https://github.com/XCSoar/xcsoar-data-repository/pull/101
=> SiteFiles - make it possible to pick/download FLARM device database

NEWS.txt, src/Dialogs/Device/DeviceListDialog.cpp
This adds labels for Temperature and Humidity to the device dialog if a device provides that data.
=> Device Manager: Show if sensor data is available

python/src/Airspaces.cpp, python/src/Flight.cpp, python/src/PythonConverters.cpp, python/src/Util.cpp
`PyArg_ParseTuple()` already calls `PyErr_SetString()` with a descriptive message, and by overriding that message we make it much harder to debug broken calls
=> python: Keep original exceptions for argument parse failures

build/libnet.mk
The HTTP client is not used at all by the Python distribution, but the `pkg-config` call will still fail if `libcurl` is not available at buildtime. This PR explicitly disables the HTTP client when building the Python distribution so that `pkg-config` is never called.
=> build/libnet: Disable `HAVE_HTTP` when building Python distribution

AUTHORS, NEWS.txt, src/Dialogs/Task/Manager/TaskManagerDialog.cpp, src/Dialogs/Task/Manager/TaskMapButtonRenderer.hpp
This patch addresses Ticket 3930. A valgrind trace is attached to that ticket. A core file is available on request.
=> Ticket 3930 - Task Editor Crashes

AUTHORS, NEWS.txt, build/driver.mk, src/Device/Driver/AirControlDisplay.cpp, src/Device/Driver/AirControlDisplay.hpp, src/Device/Register.cpp, test/src/TestDriver.cpp
Driver for the altimeter functionality of the Air Avionics - Air Control Display in accordance with the Installation Manual 2.0. Driver has been tested on my Openvario.
Ref.: #161
=> Driver for altimeter functionality of Air Control Display

src/Tracking/SkyLines/Glue.cpp
We have migrated SkyLines to a new server today, and apparently the v6.8.x branch still has the hardcoded IP in it. This commit changes the code to use the new IP. The old IP still works for now as we have set up UDP forwarding, but it will be turned off in the near future, so it would be good to get this released soon.
=> Update SkyLines server IP

src/Device/Driver/KRT2.cpp
~~WORK IN PROGRESS~~
This commit adds the redeclaration of CMD_TIMEOUT at namespace
scope as required before C++17. This commit is introduced in order
to fix a potential gcc bug, where gcc 6.3 and 8.3 doesn't inline
the variable (despite the constexpr modifier).
=> Driver/KRT2: Add workaround for possible GCC bug

src/Computer/RouteComputer.cpp, src/Computer/StatsComputer.cpp, src/Logger/LoggerFRecord.cpp
This commit adds the redeclaration of those variables at namespace
scope as required before C++17. This commit is introduced as a
workaround for gcc (6.3 and 8.3) which don't inline the variables
(despite its constexpr modifier).
Fixes XCSoar#195.
=> Logger/FRecord: Add redeclaration of constexpr variables

src/FLARM/List.hpp
The previous version of this function used list.append, which (other than an assert) assumes that the fixed size list of 25 FLARM traffic entries is not already full.
When the destination array (a TrivialArray, which uses std::array atm) is already full and we request an out-of-bounds index, this will not result in an error of any kind. Std::array also does not perform bounds checking:
https://en.cppreference.com/w/cpp/container/array/operator_at
I explicitly try to allocate a new slot in the TrafficList and check if it is not already full. If it is, there is no use in trying to add any more traffic and I abandon the Complement all-together.
=> Don't try to add more FLARM targets to an already full list

Data/Input/default.xci, build/kobo.mk, build/main.mk, src/Dialogs/LockScreen.cpp, src/Dialogs/LockScreen.hpp, src/Input/InputEvents.cpp, src/Input/InputEvents.hpp
A button in the main menu brings up a small modal dialog with just a button, that makes all the screen unresponsive to touch, except for the button area.
The button itself does nothing, it just closes the dialog and restores the touch screen functionality screen wide.
=> add a function to lock the screen and avoid unintentional touches

doc/manual/fr/ch11_configuration.tex
Fixed light for mapping comes from Nord-West, not North-Est
=> Doc: FR: Config: Fix light: NW

doc/manual/fr/XCSoar-manual-fr.tex
LaTeX package frenchle is obsolete (see https://www.ctan.org/pkg/frenchle).
Using babel French instead.
=> Manual: Fr: French LaTeX package update

doc/manual/fr/gpl.tex
The French manual contains the text of the license GPL v3, while XCSoar is under GPL v2 (https://github.com/XCSoar/XCSoar/blob/master/COPYING), as properly mentioned in the English manual.
This PR adds the correct version of the GPL license (i.e. V2) to the French manual, with both the English (official) text and an unofficial translation in French.
=> Doc: French: GPL: 3 --> 2

src/ApplyExternalSettings.cpp, src/Device/Driver/KRT2.cpp, src/NMEA/ExternalSettings.cpp, src/NMEA/ExternalSettings.hpp
When receiving an STX frame (identical to the one we send), update the Computer Setting for either active or standby frequency.
=> Update Active and Standby Radio Frequency setting from KRT2

doc/manual/toc.tex
Using package tocloft (as suggested in PR #268, package introduced by PR #307).
Supersedes PR #268.
**Rationale:**
Even when the documents using the xcsoar.sty file where producing text in sans serif font (see PR #267), the titles in the table of content was in sans serif. For example: https://download.xcsoar.org/releases/6.8.11/XCSoar-manual.pdf .
Moreover, the section numbers were sometimes touching the section titles. 
With this PR, the titles in the table of contents uses the same font style (i.e. sans serif) as the rest of the document, and there is always a space between the section number and title.
Before:
After:
=> Table of contents: Better font and layout (using package tocloft)

doc/manual/xcsoar.sty
Superseeding PR #267.
Basically, same as PR #267 and adding the package tocloft for later use (see discussion in PR #268).
Rationale:
For some time I was wondering why the manual in version 6.8.11 was in sans serif fonts (https://download.xcsoar.org/releases/6.8.11/XCSoar-manual.pdf) while the more recent 7.0 manual was in serif (https://download.xcsoar.org/nightly_builds/7.0_preview14~git%23923cf10d/manual/XCSoar-manual.pdf).
Removing the helvet package from the xcsoar style file solved the issue.
Moreover, the difference in font style when \emph{} is used is reestablished.
Note: the serif font in the table of contents is another issue (coming PR)
Before:
After:
=> Sans serif font are back, getting ready to use package tocloft

src/Device/Driver/AirControlDisplay.cpp, test/src/TestDriver.cpp
As described in the title, this code change in the ACD driver makes use of the newest Infobox addition for the radio frequencies.
=> Read primary and secondary frequency from ACD to display in XCS infobox

doc/manual/en/ch10_infobox_reference.tex, src/InfoBoxes/Content/Factory.cpp
- Previous description implied that QNH needs to be set (this is not the case if barometric altitude is available -> if barometric altitude is available, the FL value is referenced to 1013 hPa)
- Description changed to take into account fallback FL calculation from GPS altitude (in this case the QNH does need to be set)
- Description changed to make user aware that red "FL" label indicates fallback GPS flight level calculation
=> Update Flight Level infobox description

doc/manual/en/ch08_avionics_and_airframe.tex
- Altair removed because not suppported by XCSoar 7.
- Change in one menu location.
- LaTeX syntax
=> Doc: EN: Chap 8: minor improvements

src/InfoBoxes/InfoBoxLayout.cpp
Bugfix: it ignores the “InfoBox geometry” parameter when the screen is exactly square.
I eliminate the square case, which is now treated the same as portrait.
Observe the bug: running “xcsoar -square”, then resize the window to portrait or landscape. The square case has 5 InfoBoxes regardless of the “InfoBox geometry” setting.
=> fix InfoBox geometry for square layout

src/ActionInterface.cpp, src/RadioFrequency.hpp
I'm not too sure about this, so pointers are more than welcome.
I am not sure if adding the two modulo-checks in `SetKiloHertz()` are a good idea. They look heavy. Yet it does prevent parsing clearly invalid frequencies.
=> Implement OffsetKiloHertz for 8.33 kHz radio channels

src/Screen/OpenGL/Init.cpp
This solves issue #351.
Tested on TARGET=UNIX OPENGL=y, as discussed in issue #351.
=> Multiply rotation (if there is one) with projection_matrix in OpenGL software rotation

src/Input/InputEvents.cpp, src/MapWindow/GlueMapWindow.hpp, src/MapWindow/GlueMapWindowOverlays.cpp, src/Menu/MenuBar.cpp, src/Menu/MenuBar.hpp
Second attempt at fixing issue #234. (Previous was PR #289 )
Added `GlueMapWindow::SetBottomMargin(unsigned int)` to be called whenever buttons are drawn (happens in `InputEvents::drawButtons(...)` ), so that `GlueMapWindow::DrawMapScale(..)` can avoid drawing in that area when in portrait mode.
Calling  `GlueMapWindow::SetBottomMargin(unsigned int)` triggers `QuickRedraw()`
=> Panmode map scale render fix

doc/manual/en/lua.tex
When using the `\xc` shortcut latex skips the typed white-space that comes after it. So I added a control space `\␣`.
=> Fixed trailing space after \xc command

.gitlab-ci.yml
This would enable the upload of nightlies for every commit in the master branch to download.xcsoar.org.
Since this are ~6GB per commit currently, I propose to upload artifacts only for preview releases, but using DEBUG=n and reduced into a directory structure which resembles the structure known from the existing releases.
=> WIP: Fix upload of nightlies to download.xcsoar.org

src/Device/Driver/OpenVario.cpp
1. the BU sentence (Bugs) included a CR before the checksum
2. the WL sentence (Wing Load) had inappropriate number format
=> fix 2 malformed NMEA sentences in the OpenVario device driver.

build/libboost.mk
This PR fix the problem when the build process wants to download boost from the alternative server (BOOST_ALTERNATIVE_URL) due to a failure on the primary (ex. return code HTTP Error 403, happened a few times in the past).
Unfortunately the alternative url did not work (File gone - probably newer version of requested archive available).
=> Fix BOOST_ALTERNATIVE_URL

doc/manual/en/developsetuplinux.tex, ide/provisioning/add-debian-unstable.sh, ide/vagrant/Vagrantfile
This updates the vagrant box to debian-10. We are also switching to the generic box provider from vagrantup. These boxes are built by lavabit and the entire [process](https://github.com/lavabit/robox/blob/master/http/generic.debian10.vagrant.cfg) is here on github.
The boxes support all possible providers for vagrant, such as: virtualbox,hyperv,libvirt and even parallels on OSX.
The clone process also now initializes submodules without which a build would fail.
Fixes #292 
I'm not entierly happy about adding the repos in the vagrantfile. This should be a seperate script in ide/provisioning/setuprepos.sh or similar and should be references by both docker and vagrant.
=> Vagrant debian10

src/Dialogs/Settings/Panels/SiteConfigPanel.cpp, src/Repository/FileType.hpp, src/Repository/Parser.cpp
This adds an additional file type to the repository parser for waypoint-details files. As this type is now known, the file picker now shows the Download button for the waypoint-details list.
=> Make Waypoint Details downloadable via download dialog

src/Gauge/GaugeVario.cpp
fixes #397 The average needle is painted with a pen instead a brush, therefore also the pen color is selected for V6.8.xx.
=> Fixes 30s average needle color when boxes are inverted for v6.8.xx

src/Dialogs/Settings/Panels/VarioConfigPanel.cpp, src/Gauge/GaugeVario.cpp, src/Gauge/VarioSettings.cpp, src/Gauge/VarioSettings.hpp, src/Profile/ProfileKeys.cpp, src/Profile/ProfileKeys.hpp, src/Profile/UIProfile.cpp
fixes #178 by showing the average thermal climb ratio instead of current climb ratio. The color bar shows unchanged the current thermal. While not climbing the last average climb ratio is shown. This view allows a fast assessment of the current thermal by comparing the 30s average and the average over thermal.
=> fixes #178 added an optional vario needle mode

src/Screen/OpenGL/Init.cpp
Initial fix (8bd49afa25e112f3d5f377dfa1ad72656effc35d) caused rendering problems (black screen) on platforms in which `SOFTWARE_ROTATE_DISPLAY` is not defined (e.g. Android). It was reverted in 6ef5768a073f7fd07442dc6f897f4fe7220d460e.
Tested on Android, but was reproducible on regular UNIX as well. The problem with original `projection_matrix *= glm::ortho` fix is that `projection_matrix` is initialized with zero matrix.
Fixes #351.
=> Fix software display rotation (again)

src/Dialogs/Settings/Panels/WaypointDisplayConfigPanel.cpp, src/Renderer/WaypointRenderer.cpp, src/Renderer/WaypointRendererSettings.hpp
This patch adds an additional mode for the display of “Arrival height” at a
waypoint, comprising both geometrical Glide Ratio and arrival altitude around
terrain.
Motivation: I find it safer to make my in-flight navigation decisions based
on GR (eg I decide not to go further than GR 20 from the closest landable on
a glider with theoretical L/D of 40), but the arrival altitude adds
confidence. In the current version it’s one or the other, this patch adds an
entry “Required GR & terrain glide” to the existing “None / Straight glide /
Terrain avoidance glide / Straight & terrain glide / Required glide ratio”
Files updated:
src\Renderer\WaypointRendererSettings.hpp
- Addition of REQUIRED_GR_AND_TERRAIN to  class ArrivalHeightDisplay
src\Renderer\WaypointRenderer.cpp
- Addition of code to …
=> Renderer: New waypoint display: GR + arrival alt

src/IGC/IGCParser.cpp, test/src/TestIGCParser.cpp
=> IGCParser: Add support for long-form `DTE` header

python/src/Flight.cpp
with Python 3.6 and below, using `char*` is fine, but 3.7 and above are failing to compile without this fix.
=> python/Flight: Use `const char*` for `PyUnicode_AsUTF8AndSize()` return value

.github/ISSUE_TEMPLATE/Bug.md, .github/ISSUE_TEMPLATE/Feature.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
Adds issue templates for types Bug and Feature requests, as well as a PR template for pull requests.
Also includes a link to the forum which is shown when the contributor is presented with a menu where they select which type of issue they want to open.
=> Add GitHub issue and PR templates

build/test.mk, src/Repository/AvailableFile.hpp, src/Repository/Parser.cpp, src/Util/HexString.hpp, test/src/TestHexString.cpp
- moved MD5 files to Util instead of Logger
- added `sha256_hash member to AvailableFile struct
Preparing a better solution for #417
=> Add checksum field to Repository/AvailableFile

NEWS.txt, src/Dialogs/Settings/Panels/GaugesConfigPanel.cpp, src/MainWindow.cpp, src/Profile/ProfileKeys.cpp, src/Profile/ProfileKeys.hpp, src/Profile/UIProfile.cpp, src/UISettings.cpp, src/UISettings.hpp
Allow user to select position of ThermalAssistant.
Includes avoiding infoboxes if in the way.
=> Select position of ThermalAssistant

build/python/build/libs.py
Update OpenSSL to 3.0.0-alpha4
=> build/python/libs: update OpenSSL to 3.0.0-alpha4

src/Event/Poll/Linux/Input.cpp
This adds an explicit include for a header which wasn't resolved automatically in my environment when trying to build v6.8.x
Closes #445
=> Missing include of errno (@nico-krais)

src/Hardware/DisplayGlue.cpp, src/Hardware/DisplayGlue.hpp, src/Screen/Custom/TopWindow.cpp, src/Screen/TopWindow.hpp, src/Startup.cpp
On devices with fixed physical screens (such as Openvario) the orientation of initial screens, such as Fly/Simulator selection or profile selector might appear sideways (see the example screenshot below). 
This PR adds ability to autodetect the display orientation from the OS environment and implements detection from linux console orientation when XCSoar is run under DRM/KMS (Openvario case).
See the commit messages for more detailed description.
=> Detect initial screen orientation

ide/docker/Dockerfile, ide/docker/README.md
* Add `libglm-dev` to the debian packages to fix `glm/fwd.hpp` missing file error
* Since XCSoar can now be run inside the container, also include `gdb` for debugging inside the container. 
* Finally, to make running XCSoar inside the docker container slightly nicer, I added a way to mount the xcsoar data folder to the example in the readme (which had a typo that I also took the liberty to fix).
=> Ide docker updates

src/Polar/PolarStore.cpp
Adds the polar of 'D-43' to the PolarStore
None
=> Polar/PolarStore: Add D-43 polar

.github/workflows/build-container.yml
Is this builds the XCSoar-build container automatically, and pushes it to the ghcr.io/XCSoar registry. 
With this we have an official build environment for anyone ready to pull.
This also lessens the dependence on github, travis, or cicle-ci for building xcsoar, and even self-hosted building is possible.
At a later stage its planned to use it for the CI so that we have a consistent build environment and replace circle.ci.
=> github/actions: build container creation/upload

src/Hardware/DisplayGlue.cpp, src/Hardware/DisplayGlue.hpp, src/Screen/Custom/TopWindow.cpp, src/Screen/TopWindow.hpp, src/Startup.cpp
This Pull Request should insert the same code for detection of orientation (f.e. on OpenVario) like pr #453 from kedder on 23 Jul in branch v6.8.x, because the stable branch has the same problem!
=> Detect initial screen orientation for 6.8.x

build/driver.mk, src/Device/Driver/XCVario.cpp, src/Device/Driver/XCVario.hpp, src/Device/Register.cpp
New protocol "$PXCV" to support new device, the XCVario ( https://xcvario.de ) featuring vario, TE, airspeed, temperature, AHRS (roll/bank, 3D acceleration), and bidirectional exchange for cruise/vario mode, MC, Ballast, Bugs and QNH. 
The new protocol is implemented in here, https://github.com/iltis42/OpenIVario and shall be the default for new series of XCVario's for 2021.
The new protocol allows all the above features, what won't be possible otherwise, and has been derived as a cherry pic from elements of OpenVario, Eye-Sensorbox, Borgelt, and Cambridge protocols.
=> XCVario Driver

doc/manual/en/compiling.tex
Current development document for Android is a little bit out of date.
The requirement was change long time ago in b583c5bf48ae3a7c83d60641ef14c03918a470df
Here's the updated version:
=> Update Android build requirement document

src/InfoBoxes/Content/Factory.cpp, src/InfoBoxes/Content/Thermal.cpp, src/InfoBoxes/Content/Thermal.hpp, src/InfoBoxes/Content/Type.hpp
New Infobox that shows the time in the thermal
=> New Infobox - Time in Thermal

ide/provisioning/install-debian-packages.sh
Solve Issue #519 'In Docker some packages missing for an error free run'
Add 3 Packages to the docker-provisioning-file: 
* overall build environment: cmake, ninja-build
* linux target: libglm-dev
The same packages are needed for a build in the native environment
=> Add missing packages for a clean docker build run

android/AndroidManifest.xml, android/testing/AndroidManifest.xml
In https://github.com/XCSoar/XCSoar/commit/fb8370c2ed5df0e69a1055e3d53d922847ae2ea4 there was an attempt to fix full screen size for Android device that aspect ratio greater than 16:9
But there's a bug in that fix, we suppose to replace `ratio_float` with the actual number based on the document: https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html
So the fix wasn't actually works.
This should be a real fix.
before|after
------|-----
=> Fix android.max_aspect for Android device that aspect ratio greater than 16:9

build/driver.mk, src/Device/Driver/XCVario.cpp, src/Device/Driver/XCVario.hpp, src/Device/Register.cpp
As discussed in Forum, now ported from master branch to branch 6.8.x as of user requests (>200 XCVario devices in field as of today) to make this more commonly available.
The new protocol "$PXCV" is made to support a new developed OpenSource device, the XCVario ( https://xcvario.de ) featuring Vario, TE, airspeed, Temperature, AHRS (roll/bank, 3D acceleration), and bidirectional exchange for cruise/vario mode, MC, Ballast, Bugs and QNH, running on cheap hardware available commonly now.
The protocol is implemented XCVario here, https://github.com/iltis42/XCVario and shall be the future default for new series of XCVario's in 2021.
The protocol allows all the above features, what won't be possible otherwise, and has been derived as a cherry pic from elements of OpenVario, Eye-Sensorbox, …
=> XCVario driver ported to 6.8.x branch

src/Task/ProtectedTaskManager.cpp
When manually adjusting to the previous turn point it must forget that it had visited that turn point before. If it finds this TP had been visited before it auto-increments to the next TP.
Issue #492 
This was previously addressed in PR #528 .
I misread Max' comment and started with a new PR. But when Max told me to fix the old PR it was already too late and I had delete the old branch. Sorry for this.
=> Fix adjust to previous turnpoint in a task

src/Dialogs/Weather/PCMetDialog.cpp, src/ui/canvas/gdi/GdiPlusBitmap.cpp
Unfortunately the wheather images from PC-Met are still blank in XCSoar, It was missing the setting of the image dialog with the regarded widget ;-(
See is a small but important addition to PR 540 "Reactivation PC-Met access"
=>  Reactivation PC-Met access, part 2

NEWS.txt, src/Renderer/SymbolRenderer.cpp
This bug was introduced in f143a2e6 which make plus symbol rendered as minus symbol
Closes #564
after:
=> Fix plus symbol rendering in SymbolRenderer

src/Kobo/Model.cpp, src/Kobo/Model.hpp, src/Kobo/System.cpp, src/ui/canvas/fb/TopCanvas.cpp
Adds Kobo Nia support for WiFi and USB Storage export features. Note that XCSoar 7 does not currently boot on the Kobo Nia due to missing /dev/ entries, which needs to be addressed to actually support the Nia.
=> Basic Kobo Nia support - WiFi and USB Storage export.

NEWS.txt, src/Dialogs/Settings/Panels/TrackingConfigPanel.cpp
Use the existing tracking intervals list for SkyLines also for LiveTrack24.
Currently LiveTrack24 allows tracking intervals between 5 seconds and 1 hour using 5 second increments.
Intent: Allow LiveTrack24 tracking intervals smaller than 5 seconds.
none
Caveats
--------
Users with an existing setting of `TrackingInterval` outside of the values specified in the `tracking_intervals` array (e.g. "1800") will have their tracking interval set to 1 second.
=> Settings/TrackingConfigPanel: same tracking intervals for Livetrack24 as for SkyLines

Data/Input/default.xci, NEWS.txt, doc/manual/en/ch02_user_interface.tex, doc/manual/en/ch03_navigation.tex, doc/manual/en/ch04_xc_tasks.tex, doc/manual/en/ch11_configuration.tex, src/Device/Descriptor.cpp, src/Device/Descriptor.hpp, src/Device/Driver.cpp, src/Device/Driver.hpp, src/Device/Driver/FLARM/Device.cpp, src/Device/Driver/FLARM/Device.hpp, src/Device/MultipleDevices.cpp, src/Device/MultipleDevices.hpp, src/Dialogs/Settings/Panels/TaskRulesConfigPanel.cpp, src/Dialogs/Task/Manager/TaskPropertiesPanel.cpp, src/Engine/Task/Ordered/StartConstraints.cpp, src/Engine/Task/Ordered/StartConstraints.hpp, src/Input/InputEvents.hpp, src/Input/InputEventsActions.cpp, src/Logger/Logger.cpp, src/Logger/Logger.hpp, src/Profile/ProfileKeys.cpp, src/Profile/ProfileKeys.hpp, src/Profile/TaskProfile.cpp, src/Task/Deserialiser.cpp, src/Task/ProtectedTaskManager.cpp, src/Task/ProtectedTaskManager.hpp, src/Task/Serialiser.cpp
This adds support for Pilot Event start procedure, recently introduced for use in gliding competitions. See  [rules for world and continental gliding championships](https://www.fai.org/sites/default/files/sc3a_2020a.pdf), page 28, 29 for more details.
This PR introduces a new button, available under Nav -> Nav -> Pilot Event. When pressed, a time window for a valid start is configured according to two new user-configurable settings for the task. This feature takes advantage of existing "start open time" and "start close time" parameters as well as existing "Start open" and "Start reach" infoboxes to aid the pilot.
Expected mode of operation: when "Pilot Event" start is used in a competition day, pilot will set "PEV start wait time" …
=> Pilot Event (PEV) start

ide/provisioning/install-debian-packages.sh
i was able to compile the kobo target with these dependencies.
=> kobo-build: add missing includes for gcc

NEWS.txt, src/Device/Driver/FLARM/Device.cpp
Pilot Event NMEA sentence for PowerFLARM devices was incorrect in initial implementation. Contrary to FLARM documentation, the trailing asterisk symbol is not needed (the sentence is rejected with the asterisk as invalid).
This was positively tested by PowerFLARM owner.
=> Fix pilot event (PEV) sentence for PowerFLARM

NEWS.txt, src/Task/Deserialiser.cpp
In task files, generated by external tools some task attributes might be missing in the task xml file. When loading such tasks we want to keep task default values, set in the XCSoar system settings.
For example, tasks, gnerated by soarscore.com are missing start and finish height settings. This is on purpose, because this information is not available on soaringspot.com, which is used as a source for the task generation. Instead of putting some arbitrary values in the generated task xml file, attributes, such as `finish_min_height` or `finish_min_height_ref` are simply omitted. When XCSoar loads such a task file, it correctly sets `FinishConstraints.min_height` to the value from the task defaults, however `min_height_ref` gets always reset to "AGL". When competition rules specify min. …
=> Use task defaults when height ref is missing in task file

NEWS.txt, src/Dialogs/Settings/Panels/LayoutConfigPanel.cpp, src/InfoBoxes/InfoBoxLayout.cpp, src/InfoBoxes/InfoBoxSettings.hpp, src/Profile/InfoBoxConfig.cpp
Adds a new 3x5 layout, aimed at modern mobile phones Aspect Ratios, exactly as done in 202d7f0faff847c74861bd8cc91969f18fb6793c
Closes #614
=> InfoBoxes/Layout: add 3x5 InfoBoxes layout

build/libdata.mk, build/resource.mk, src/Dialogs/dlgCredits.cpp
Having the changelog accessible from within XCSoar would be pretty convenient - at least for me.
Made a mistake and couldn't re-open #713.
=> Dialogs/dlgCredits: add Changelog

NEWS.txt, src/Dialogs/Waypoint/WaypointInfoWidget.cpp, src/Engine/Waypoint/Waypoint.hpp, src/Engine/Waypoint/Waypoints.cpp, src/Renderer/WaypointListRenderer.cpp, src/Waypoint/WaypointReaderSeeYou.cpp, test/src/TestWaypoints.cpp
The ICAO field aka short name is currently unused. This parses the entry and displays it in the waypoint details dialog. It also makes the short name searchable. 
Waypoint Details
Waypoint Search List Dialog
=> Extend SeeYouReader to parse the ICAO Field in CUP files

NEWS.txt, build/main.mk, src/Device/Descriptor.cpp, src/Device/Driver/LX/Declare.cpp, src/Device/Driver/LX/Internal.hpp, src/Device/Driver/LX/LXNAVVario.hpp, src/Device/Driver/LX/Logger.cpp, src/Device/Driver/LX/Mode.cpp, src/Device/Driver/LX/Parser.cpp, src/Device/Driver/LX/Register.cpp, src/Device/Driver/LX/Settings.cpp, src/Device/Driver/PosiGraph.cpp, src/Dialogs/Device/DeviceListDialog.cpp, src/Dialogs/Device/LX/LXNAVVarioConfigWidget.cpp, src/Dialogs/Device/LX/LXNAVVarioConfigWidget.hpp, src/Dialogs/Device/LX/ManageLXNAVVarioDialog.cpp, src/Dialogs/Device/LX/ManageLXNAVVarioDialog.hpp, src/NMEA/Info.hpp, test/src/TestDriver.cpp
Fixes issues with declaring tasks and other comms with LXNAV S series varios.
Based on original work from LXNAV located here: https://github.com/XCSoar/XCSoar/pull/220/
Tested with an LXNAV S100 vario. No testing has yet been performed with other LXNAV Varios or their passthrough capability with the Nano.
Closes #688 
Update to indicate test steps taken with S100 vario:
1. NAV->Task->Manage->Declare; XCSoar indicates success, S100 receives task.
2. Config->Flight; made changes to ballast and bugs. Vario recevies updated values. 
3. Changed manual MC value; vario receives the updated value.
4. Changed MC, ballast and bugs at vario; XCSoar receives the updated values.
5. …
=> Fix for LXNAV Varios

NEWS.txt, src/Dialogs/Settings/Panels/WaypointDisplayConfigPanel.cpp, src/Dialogs/Waypoint/dlgWaypointEdit.cpp, src/Renderer/WaypointRenderer.cpp, src/Renderer/WaypointRendererSettings.hpp, src/Waypoint/CupWriter.cpp
Makes the short name selectable in the lables setting. If unavailable fall back to 5 letters of the full name.
=> map: ability to show the short name of waypoints

src/Device/Driver/XCVario.cpp
Handle ballast change locally in XCVario driver instead from CAI302 inherited method by a float with 3 decimals precision instead of integer with fractions of 10% in order to see exactly same ballast on both sides.
Historically the Cambride devices cannot provide more precision as fractions of 10% from max ballast, as of hardware limitation of input device. This limitation does not apply for XCVario, and there is no reason for this granularity when XCS is the source of info, correctly noted by the filed issue from @hjr. Hence the issue opened for XCVario needs a changed here, XCVario already covers parsing float precision, and has been successfully tested with this …
=> XCVario driver: Fix unprecise ballast sync from XCS and move to GetHectoPascal()

src/Device/Driver/BorgeltB50.cpp, src/Device/Driver/XCVario.cpp, test/src/TestDriver.cpp
Invert Cruise/Circling mode in NMEA parsing of Borgelt B50 driver and same issue in XCVario code that took over wrong logic from there.
Actually the Cruise Mode is transmitted as a "1" in the corresponding bit in native Borgelt B50 protocol, even the comment in the code indicates this, hence the parsing in the corresponding driver does exactly vice and CIRCLING is chosen once there is a one reading in the 'G' field for cruise, indicated by a circling arrow in the Vario gauge in XCSoar. 
See here the manual from B50, and also the  
// inclimb/incruise 1=cruise,0=climb, OAT
comment in the source file which also says 1=cruise.
B50 Manual (see last page): …
=> Fix inverted cruise/circling mode in Borgelt and XCVario protocol

doc/manual/en/ch10_infobox_reference.tex, src/InfoBoxes/Content/Factory.cpp
Followed suggestions from glider buddies not understanding the "Wind V", or "V Wind" headline in the box. 
Renaming the info box long names so that all wind related boxes group together.
=> Allign box nomenclature for Wind info boxes.

src/Hardware/DisplayDPI.cpp, src/Kobo/Model.cpp, src/Kobo/Model.hpp, src/Kobo/System.cpp, src/ui/canvas/fb/TopCanvas.cpp
Customized for CLARA_HD the following:
DPI, battery status, poweroff(), Wifi, Export USB,
frame_sync and reboot.  rcS was previously customized.
All else is common to all Kobo models and was left unchanged.
For each instance of model specific code, CLARA_HD was added as appropriate
following the coding style of the particular source file.  All changes were made
to leave other models unaffected and the changes were tested on a Clara HD 
successfully.
No current issue is addressed but this adds one common model of Kobo and
provides functionality that was missing.
=> Add CLARA_HD to list of Kobos

NEWS.txt, src/Kobo/SystemDialog.cpp
Disable OTG for Clara HD to avoid bricking the unit since the kernel is not compatible
=> Disable OTG for Clara HD and update NEWS

NEWS.txt, src/Kobo/SystemDialog.cpp
Enable and control the backlight of a Kobo Glo HD from the system dialog.
=> Control backlight brightness of the Kobo Glo HD in the system dialog

src/Device/Declaration.hpp, src/Device/Driver/FLARM/Declare.cpp, src/Device/Driver/FLARM/TextProtocol.cpp, src/Device/Driver/FLARM/TextProtocol.hpp
Allows up to 10 turnpoints per task (which is the same as the limit was previously, and the maximum a FLARM device will accept).
=> Amend FLARM device task declaration to use waypoint Short Name instead of index

NEWS.txt, src/Dialogs/Settings/Panels/LayoutConfigPanel.cpp, src/InfoBoxes/InfoBoxLayout.cpp, src/InfoBoxes/InfoBoxSettings.hpp, src/Profile/InfoBoxConfig.cpp
Admittedly this is yet another hard-coded infobox layout that won't be useful to everyone, but this one is pretty useful on a 7" display (eg the 7" Openvarios, of which there are a lot around), particularly in portrait mode. Uses less screen real-estate than the existing 3x5 layout, and is easily readable on a 7" screen mounted in an instrument panel.
=> Add 3x6 InfoBox layout

src/Kobo/Kernel.cpp, src/Kobo/Kernel.hpp, src/Kobo/KoboMenu.cpp, src/Kobo/SystemDialog.cpp
With Clara HD, OTG host mode is no longer tied to custom kernel
so this splits IsKoboOTGKernel into IsKoboCustomKernel and
IsKoboOTGHostMode.  This doesn't change anything but sets the
stage for adding OTG to Clara HD (and any others that have OTG
in the factory kernel).
=> Split IsKoboOTGKernel into two routines

src/Device/Descriptor.cpp
The function have to return with false if port is NOT a nullptr!
This prevents the output via the port
=> DeviceDescriptor - wrong port check

NEWS.txt, android/src/UsbSerialHelper.java
add USB VID/PID pairs for SoftRF Academy and ES Editions into (Android) 'white list' of USB devices
=> add SoftRF Academy and ES into 'white list' of USB devices

NEWS.txt, build/kobo.mk, kobo/rcS, src/Kobo/Kernel.cpp, src/Kobo/Kernel.hpp, src/Kobo/SystemDialog.cpp
Added OTG support including modules for serial, sound and
networking.  Note the modules are included in the release
separately (just as are the OTG kernels for other models).
If they are absent (e.g. a local build), no failure will occur.
NOTE!!! To make this complete, a tgz file must be put on the build server
in the SAME folder as the OTG kernels already present.  Failure to
do this will NOT cause a failure, just a loss of OTG functionality for 
Clara HD.  Let me know who to send the tgz file to.  I have tested it
on my build setup.
closes #794
=> Add OTG to Clara HD

AUTHORS, NEWS.txt, build/main.mk, src/Dialogs/FilePicker.cpp, src/Input/InputEvents.hpp, src/Input/InputEventsActions.cpp, src/Logger/ExternalLogger.cpp, src/Repository/FileType.hpp, src/contest/weglide/UploadIGCFile.cpp, src/contest/weglide/UploadIGCFile.hpp
Add some components to prepare the upload feature
* simple date picker for date of birth selection
* integer selection picker for large numbers
* curl  UploadFile component
* Setting the relevant data in the 'Config/Setting/WeGlide Cloud'-Panel and in the 'Plane'-Panel
* Uploading the IGC file with 3 options:
*  1st: Direct upload automatically after downloading file from logger (all necessary data have to be set and additional the flag 'automatic upload'
* 2nd: Calling the IGC-FilePicker with a (self defined) lua gesture or keypress event
* 3rd: Upload directly over a lua file
The upload is following the proposal Issue #505 from Bomilkar.
The 'Downloading WeGlide …
=> WeGlide Uploading IGC files

NEWS.txt, android/src/UsbSerialHelper.java
add VID/PID pair(s) for SoftRF Lego into Android 'white list' of USB devices
=> add SoftRF Lego into 'white list' of USB devices

src/Form/Edit.cpp, src/Form/Form.cpp, src/Renderer/TextRowRenderer.cpp, src/ui/control/custom/LargeTextWindow.cpp
=> ui: left-hand padding for Lists/RowForm/LargeTextWin

doc/manual/de/ch03_navigation.tex, doc/manual/de/ch04_xc_tasks.tex, doc/manual/de/ch05_glide_computer.tex, doc/manual/de/ch06_atmosphere_and_instruments.tex, doc/manual/de/ch11_configuration.tex, doc/manual/de/ch13_history.tex, po/de.po
Replace "Algorythmus" (and any inflections) with "Algorithmus" in German docs.
=> doc/manual: correct typos in german manual

Data/Status/default.xcs, NEWS.txt
The messages are displayed only 1.5s currently. 
That is too short for any situation, especially in a cockpit.
=> Increase Message Timeouts to 2.5s

src/Airspace/AirspaceParser.cpp, src/net/http/Global.cxx, src/net/http/Global.hxx
Two functions that throw runtime errors, that are encapsulated by other function calls, that have noexpect defined.
=> Critical Errors found by Codacy

src/Device/Driver/FLARM/BinaryProtocol.cpp, src/Device/Driver/FLARM/BinaryProtocol.hpp
With catching of exception(s) and extension of a timeout period it is possible to get all downloadable flights of a flarm device in a list - and not the wrong message 'flightlist is empty'
This changes should be solve the described problem (There was mostly a difference in the view of recorded flights between reading with FlarmTool and XCSoar)
This issue is not only linked to XCSoar itself: I observed this in the last year very often only with the PowerMouse! But with the new Flarm update 7.06 I observed this on all other devices (PowerFlarm, normal Flarm, ...) I think, Flarm changed something on the timing... ;-(
=> Flarm bugfix reading flightlist

src/Input/InputEventsActions.cpp
Pointer gets out of bounds in `ScanMultiplePatterns` if pattern list isn't terminated by empty string. This results in picking up extra undefined patterns and misbehaviour.
=> Input/InputEventsActions: end pattern list with \0

src/Device/Port/TTYEnumerator.cpp, src/Device/Port/TTYEnumerator.hpp
Set a higher limit for the enumeration list.
This makes the list longer but at least the important ports entries show up again.
Closes #888
=> Filter pseudo terminals from serial port list

ide/provisioning/install-debian-packages.sh
Add development package for OpenGL math.
When I build the docker container and compile TARGET=UNIX it complains about this missing package.
=> IDE: add missing package for OpenGL math

ide/provisioning/install-debian-packages.sh
Reverts XCSoar/XCSoar#959
Library is included as submodule.
=> Revert "IDE: add missing package for OpenGL math"

AUTHORS, build/kobo.mk
The kernel binaries were not included or fetched from a known
source.  They were required to be put in a fixed directory
on every machine on which KoboRoot.tgz was built.  This made
it inaccessible to add/change/edit by PR.
Closes #880
=> Move kernel binaries into repository

src/Tracking/SkyLines/Client.cpp
The documentation for FileDescriptor::Close() states that it should
only be called if File::Descriptor::IsDefined() is true. So do that.
=> SkyLines: Honor usage conditions of FileDescriptor

src/Terrain/TerrainSettings.cpp
I think we are giving XCSoar's Terrain Renderer not enough credit.
This change changes the default setting for the renderer (which is an expert setting)
to a high brightness and lower contrast value. 
The shading is still visible and the appearance is more detailed.
Before:
After:
=> Terrain: Set contrast/brightness according to modern screens

.github/workflows/build-native.yml
Currently PR builds fail, as it tries to upload the android binary to XCSoar, which of course isn't permitted and the secrets aren't available.
=> gh: build-native only upload artifact on push

src/InfoBoxes/Content/MacCready.cpp, src/InfoBoxes/Content/Radio.cpp, src/InfoBoxes/Data.cpp
Sets MC to Green if a value is configured manually. 
Sets Radio Active to Green if a value is configured. 
Sets Radio StandBy to Blue as an armed value. 
According to:
https://www.faa.gov/documentLibrary/media/Advisory_Circular/AC_25-11B.pdf
Table 5-2. Specified Colors for Certain Display Features
=> Color MC and Radio Infoboxes according to state

android/src/UsbSerialHelper.java, android/src/UsbSerialPort.java
UsbSerial fully supports multi interface devices. This change makes UsbSerialHelper.java capable providing this functionality to the main program. Some changes were necessary since the code of UsbSerialHelper assumed a one to one relationship of device and port, which is not the case for multiport devices.
Although quite some lines needed changing, the behaviour for single Port devices should not have changed at all.
For multiport devices however entries for each port (=interface) will be available and managed with this change.
https://github.com/XCSoar/XCSoar/issues/968
Closes #968
=> Make UsbSerial work with multi-interface devices. (e.g. FTDI4232)

src/Dialogs/Waypoint/WaypointList.cpp, src/Waypoint/WaypointList.cpp, src/Waypoint/WaypointList.hpp
Retains filtering name and shortname but deletes duplicates
(e.g. when the shortname is the same as the name).  Also
eliminates duplicates when distance is the filter.  Bonus: this
should slightly speed up rendering of the waypoints on the map.
Closes #958
Closes #816
=> Eliminate duplicate waypoints in list

ide/provisioning/install-debian-packages.sh
=> install-debian-packages: add missing texinfo package

Data/icons/map_small.svg
`viewBox`, a standard SVG attribute, frames the small dot icon so that it resizes proportionally to the prevailing icons size. Cleanup removes unneeded Inkscape metadata and redundant objects. Fixes #982
=> Data/icons/map_small.svg: Add viewBox attribute and file cleanup

AUTHORS, NEWS.txt, src/Weather/Rasp/RaspCache.cpp, src/Weather/Rasp/RaspStore.cpp, src/Weather/Rasp/RaspStore.hpp, src/Weather/Rasp/RaspStyle.cpp
> Is there a way to do this on android or to generally introduce transparency to the RASP overlays?
I don't think there presently is. 
However Topography can have an alpha value and is then rendered transparently: src/Topography/TopographyFIleRenderer.cpp
=> Weather/Rasp: Thermalmap, 15min Intervals and Rasp URLs in Repository

NEWS.txt, src/Profile/ComputerProfile.cpp
In Setup → WeGlide the 'Automatic Upload' field is saved to the profile but never loaded.
This PR will fix it.
=> WeGlide 'Automatic Upload' not persistent

ide/provisioning/install-android-tools.sh
Minor fix to the vagrant provisioning scripts.
The path formed in the if clause was invalid, thus SDK was being installed even when already there.
=> install-android-tools.sh: fix path in SDK install guard

NEWS.txt, android/res/xml/usb_device_filter.xml, android/src/UsbSerialHelper.java
add USB VID/PID pairs for SoftRF Balkan and Prime Mk3 Editions into (Android) 'white list' of USB devices
=> add SoftRF Balkan and Prime Mk3 into 'white list' of USB devices

NEWS.txt, src/Dialogs/Waypoint/dlgWaypointEdit.cpp
Currently the waypoint editor doesn't allow to save the waypoints in all the available [SeeYou CUP formats](https://downloads.naviter.com/docs/SeeYou_CUP_file_format.pdf), despite XCSoar fully supports them.
This PR adds the missing types, with the exception of "unknown".
=> WaypointEditor: support more waypoint types

NEWS.txt, build/infobox.mk, src/Computer/Settings.hpp, src/InfoBoxes/Content/Factory.cpp, src/InfoBoxes/Content/Places.cpp, src/InfoBoxes/Panel/ATCSetup.cpp, src/InfoBoxes/Panel/ATCSetup.hpp
Added a "Setup" panel to the ATC Radial info box to configure a magnetic declination value.
This allows the display of magnetic bearings to match VOR radials, which is what ATC expects.
#1010
=> ATC Radial infobox show magnetic bearings

NEWS.txt, android/src/UsbSerialHelper.java
The _(**Android** only)_ PR https://github.com/XCSoar/XCSoar/pull/995 have caused a regression that a **single** USB CDC device has become  appeared as multiple entries in the 'Device -> Port' list.
The USB device _(member of the XCSoar for Android 'white list')_ has 3 interfaces in total but only the second one is involved in actual 'USB-Serial' data transfers.
This PR applies a filter to avoid appearance of not usable USB interfaces in the 'Port'' list.
I've made a request to the author @henrik1g https://github.com/XCSoar/XCSoar/pull/995#issuecomment-1308471377 of that regressing PR but got no response since then.
There is a similar issue reported by @XCNav user …
=> apply USB Interface Class filter on 'Device -> Port' List

NEWS.txt, kobo/rcS, src/Hardware/Battery.cpp, src/Hardware/DisplayDPI.cpp, src/Kobo/Kernel.cpp, src/Kobo/Model.cpp, src/Kobo/Model.hpp, src/Kobo/System.cpp, src/Kobo/SystemDialog.cpp, src/ui/canvas/fb/TopCanvas.cpp
This PR adds support for the Kobo Clara 2E. No Bluetooth support yet.
=> Add support for Kobo Clara 2E

build/debug.mk
Unless DEBUG=n is explicitly set, use the red theme of xcsoar. 
(As XCSoar isn't using the testing branch anylonger, it can be used to differentiate debug from  builds that fly.)
=> build: indicate debug builds by red theme

NEWS.txt, kobo/rcS, src/Kobo/System.cpp
Newer busybox firmware required changes to avoid using -f (force) when using the reboot command.
Closes #953
=> Removed force on Kobo reboot

NEWS.txt, src/ActionInterface.cpp
Previously XCSoar would crash if a frequency swap was attempted without either of the frequencies being set.
=> ActionInterface: only exchange frequencies when both are defined

ide/provisioning/install-debian-packages.sh, src/util/Concepts.hxx
this is related to #1133, but also adresses some issues when building on debian with older clang version (11)
- Driver KRT2: fix "error: case value not in enumerated type 'std::byte'" when building with clang on debian
- Concepts.hxx: check clang version before using std::invocable and std::predicate (because of build failure on debian with clang11)
- install-debian-packages: add libc++abi-dev, because of linker failure
- flags.mk: disable -Wno-deprecated-experimental-coroutine, we can't use this option if the minimum clang version required is 10 (according to developer manual).
=> bugfixes clang build

NEWS.txt, src/Kobo/System.cpp, src/Kobo/System.hpp, src/Kobo/SystemDialog.cpp
Added CLARA HD backlight, CLARAs HD and 2E and LIBRA 2 colour temp
=> Fix backlight and add colour temperature to certain Kobo models

build/python/build/libs.py
Fix invalid alternative urls (binutils-2.39 and gcc-12.2.0)
During the XCSoar build process, I sometimes encountered issues with invalid alternative URLs for the binutils-2.39 and gcc-12.2.0 repositories.
This PR fixes it.
None
=> python/build/libs.py: fix invalid alternative urls

NEWS.txt, src/Dialogs/Plane/PolarShapeEditWidget.cpp
The current precision is not sufficient to fine-tune a polar. Step values have been divided by 5 to be able to use a precision common for defining polars.
=> Dialogs/Plane/PolarShapeEditWidget: increase precision

src/NMEA/EngineState.hpp, src/NMEA/Info.cpp, src/NMEA/Info.hpp
Add support for a Bluetooth LE engine sensor box. 
https://github.com/XCSoar/XCSoar/issues/1178
=> Add engine sensor box

NEWS.txt, build/test.mk, src/Device/Driver/AirControlDisplay.cpp, src/Formatter/NMEAFormatter.cpp, src/Formatter/NMEAFormatter.hpp, test/src/IGC2NMEA.cpp, test/src/TestNMEAFormatter.cpp
~~- added a short format for the DDMM.MMM location format~~
- added NMEAFormatter to format standard NMEA sentences
- updated the AirControlDisplay driver to forward GPS data via NMEA sentences to the device
- updated the CAILNAV driver to also use the new NMEAFormatter
#170 (previous attempt)
#1112 (recent request)
=> Provide GPS data to AirControlDisplay

android/src/BluetoothSensor.java, android/src/BluetoothUuids.java
The sensor board has additional sensors for atmospheric pressure and outside air temperature. These values are passed to already implemented specific listeners.
Add BLE "driver" for EngineState values with additional atmospheric pressure and outside air temperature.
https://github.com/XCSoar/XCSoar/issues/1178
=> Add BLE driver for EngineState

android/src/BluetoothSensor.java, android/src/SensorListener.java
Change parameter to onBarometricPressureSensor from Pascal to Hecto Pascal. Add comment for onBarometricPressureSensor
Wrong scaled value to `onBarometricPressureSensor`. Needs to be Hecto Pascal, passed Pascal.
https://github.com/XCSoar/XCSoar/issues/1178
=> Change BLE java driver for EngineState

doc/input_events.rst, src/Input/InputKeys.cpp, src/ui/event/android/KeyCode.hpp
On Android, when external keyboard is detected the zoom control from volume buttons is disabled. This PR adds volume input definitions, to enable user to configure volume buttons events.
I tried to use Bluetooth remote media controller (with volume up, volume down, previous, next, play/pause buttons), as an external controller for XCSoar. I could configure all buttons except volume buttons. This fixes this issue.
=> Added volume up and volume down keys definitions to input events.

doc/build.rst
Added missing slash to dependancies for the osx brew install after pkg-config
=> Developer Manual: added missing slash to the osx dependancies

src/Device/Driver/IMI/Protocol/Protocol.cpp
- Added flight_list.full() check to the loop when downloading the flights from IMI Erixx device, so the flight_list array does not overflow when the device contains more than 128 flight records.
- Added additional condition for success to the function result.
Closes #1225
=> IMI/Protocol/Protocol.cpp: stop ReadFlightList loop when flight_list is full

NEWS.txt, src/Device/Driver/FLARM/StaticParser.cpp, test/src/TestDriver.cpp
Beware: I wasn't able to test this with a real flarm yet.
=> FLARM: Parse AircraftType field as hex in PLFAA

ide/provisioning/install-debian-packages.sh
This PR adds the missing packages for targets Android and Wayland for docker build.
=> Docker build: add missing packages for targets Android and Wayland

doc/devsetup.rst
The list of provisioning scripts on the page "Setting up a development environment based on Linux" refers to the script add-debian-unstable.sh which does not exist in ide/provisioning.
=> ide/provisioning: Remove non-existent file from provisioning script list

doc/manual/en/ch01_introduction.tex, doc/manual/en/installation.tex
Change Android minimum version to 5.0 and also remove examples of devices, as they are obsolete for this version of Android.
Closes #1250
=> Manual: change minimum Android version requirement to 5.0

NEWS.txt, android/res/xml/usb_device_filter.xml, android/src/UsbSerialHelper.java
add USB VID/PID pairs for SoftRF Ham and Midi Editions into (Android) 'white list' of USB devices
=> add SoftRF Ham and Midi into 'white list' of USB devices

build/python/build/libs.py
The zlib 1.2.13 is no longer available for download at the URLs defined in libs.py. Replaced by version 1.3
Closes #1288
=> update zlib to 1.3

src/LocalPath.cpp
By not adding it to results, it never ended up in the actual data_paths.
=> Correctly consider /etc/xcsoar as a datapath

NEWS.txt, src/Gauge/BigTrafficWidget.cpp
Add 100m Radius Flarm Radar Option:
-Makes it easier to Identify teammates and tag bandits during a grid squat.
=> Add 100m Zoom option for Flarm Radar

src/NMEA/ExternalSettings.cpp
CompareBallastOverload method was used on ballast_liters by mistake. This fixes it by using the CompareBallastLitres method.
=> Fixed wrong method used to compare ballast liters

AUTHORS, NEWS.txt, src/InfoBoxes/Content/Factory.cpp, src/InfoBoxes/Content/Task.cpp, src/InfoBoxes/Content/Task.hpp, src/InfoBoxes/Content/Type.hpp
Added an infobox that shows ETA and Delta time during AAT task and only ETA in case of a racing task.
Automatically replace AAT delta time infobox by something else for racing task #970
=> Infobox that combines ETA with AAT dT

AUTHORS, NEWS.txt, src/ui/window/TopWindow.hpp, src/ui/window/custom/TopWindow.cpp, src/ui/window/poll/TopWindow.cpp
On builds like OpenVario based on Cubieboard the rendering of a mouse cursor is enabled. But even when no mouse is attached the mouse cursor is rendered on screen. With this contribution the mouse cursor will be hidden when there is no mouse activity for 10 seconds. On the event of new mouse activity the mouse will be displayed again for 10 seconds.
For now this is hardcoded for 10 seconds. It is open for debate if this is acceptable or a higher/lower value should be used. 
And if an extra settings should be introduced to let te user decide to use this feature or not.
=> hide mouse cursor after 10 seconds of inactivity

android/AndroidManifest.xml, android/testing/AndroidManifest.xml, doc/build.rst
Google enforce android-33 now. We won't be able to upload APK version without this. https://developer.android.com/google/play/requirements/target-sdk
https://developer.android.com/about/versions/13/behavior-changes-13
Some dependency is already updated in https://github.com/XCSoar/XCSoar/commit/db34adf9bd4e85d1023098ba0592d2420cb2bafc, but not Manifest file. 
I tested in my fork and it's working fine in my Pixel 7 Pro.
=> Android: update android:targetSdkVersion to 33

src/Waypoint/WaypointGlue.cpp
this closes issue #1122 because now markers will be last in the waypointlist meaning the id of the other waypoints does not change.
Moved loading the user.cup file (which contains the markers) down to after all the other waypoint files have been read. 
Closes #1122
=> Change order in which waypoint files are read

build/python/build/libs.py
After upgrading to CURL 8.4, the Android build was broken:
```
/home/runner/work/XCSoar/XCSoar/output/src/curl-8.4.0/lib/formdata.c:796:10: error: call to undeclared function 'fseeko'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
return fseeko(stream, (off_t)offset, whence);
^
```
This PR will fix it.
Build with:
`  make -j$(nproc) TARGET=ANDROID`
=> build/python/libs: fix build error for Android due to CURL 8.4.

src/Topography/shapelib/mapserver-config.h
The functions strlcpy and strlcat have been added to glibc 2.38. This pull request reflects these changes. 
XCSoar can now be built on Linux box with gcc 13.2.0
=> Topography/shapelib/mapserver-config: functions strlcpy and strlcat  have been added to glibc version 2.38

NEWS.txt, src/Kobo/WPASupplicant.cpp, src/Kobo/WPASupplicant.hpp, src/Kobo/WifiDialog.cpp
For the Wifi setup page, this PR implements parsing and interpreting the signal level as decibels (dBm) for new Kobo models.
Tested on a Kobo Mini and Kobo Libra 2.
=> Kobo/WPASupplicant: for new models, parse and interpret the signal level as decibels (dBm).

build/libio.mk, build/libwaypointfile.mk, src/Task/TaskFileSeeYou.cpp, src/Waypoint/WaypointReader.cpp, src/Waypoint/WaypointReaderSeeYou.cpp, src/Waypoint/WaypointReaderSeeYou.hpp, src/io/BufferedCsvReader.cpp, src/io/BufferedCsvReader.hpp
Technically the CSV standard lets you have newlines inside quoted items.
Adding support for this makes some minimal layout formatting of desc and user fields possible, which make them a lot easier to digest at a glance.
Here is an example of using the decs field for multi-line data
=> Csv newlines

build/libboost.mk
This PR fixes the problem where the Boost download URL attempts to register for a JFrog subscription.
Closes #1324
=> build/libboost.mk: new Boost download URL

NEWS.txt, src/RadioFrequency.cpp, src/RadioFrequency.hpp
This PR fixes the reading of radio frequency with unit "MHz" in the openAir file on Windows os.
Fix for #1345
=> RadioFrequency: ignore unit ("MHz") in Parse(std::string_view)

NEWS.txt, src/Airspace/AirspaceParser.cpp
This PR is a reimplementation for #1345
=> Airspace/AirspaceParser: ignore unit for radio frequency

NEWS.txt, android/res/xml/usb_device_filter.xml, android/src/UsbSerialHelper.java
add more USB VID/PID pairs for SoftRF Academy into (Android) 'white list' of USB devices
=> update 'white list' of USB devices with more PIDs for SoftRF Academy

NEWS.txt, src/Renderer/AirspacePreviewRenderer.cpp
black text color in airspace list like all other systems
- solving issue #1371
=> black text color in airspace list like all other systems

.github/ISSUE_TEMPLATE/Bug.md
In case someone writes just one XCSoar version number, it's not really clear whether they're referring to a version having or not having the problem, if there's a joint category for "having and not having the problem".
=> Bug.md - split XCSoar versions having/not having the problem

NEWS.txt, build/driver.mk, src/Device/Config.hpp, src/Device/Driver/Larus.cpp, src/Device/Driver/Larus.hpp, src/Device/Register.cpp, test/src/TestDriver.cpp
Larus is just another open source initiative to provide low cost, high performance avionics to glider pilots. No connection has yet been provided for the XCSoar software. This is now to be changed.
This driver was originally created by [August2111](https://github.com/August2111) for his XCSoar fork [Opensoar](https://github.com/August2111/OpenSoar). It has now been ported back to XCSoar. 
Information about the project: [Larus Github-Page](https://github.com/larus-breeze)
The devices can be ordered: [SteFly](https://www.stefly.aero/)
Specification of the NMEA protocol: [Larus NMEA specification](https://github.com/larus-breeze/doc_larus/blob/master/documentation/Larus_NMEA_Protocol.md)
Thank you for your support
=> Add Larus driver

NEWS.txt, src/Input/InputEvents.hpp, src/Input/InputEventsActions.cpp, src/Input/InputEventsSettings.cpp
=> Make map Orientation fully configurable by input events

NEWS.txt, src/InfoBoxes/Content/Factory.cpp, src/InfoBoxes/Content/Task.cpp, src/InfoBoxes/Content/Task.hpp, src/InfoBoxes/Content/Type.hpp
This change adds estimated task speed (the value currently shown as "Speed estimated" on the Status-Task panel) to the list of available infoboxes. This could be a desirable infobox in a speed record attempt flight. I recently missed such a record by less than the duration of one circle, and I'd have probably left the last thermal at least one circle sooner (and gotten the record) had I been able to see this value without having to go back and forth to the Status-Task panel to see it.
This change also changes "cross country" to "cross-country" in every infobox description that contained "cross country". Previously, infobox descriptions were inconsistent regarding whether "cross country" or "cross-country" was used. It also tidies up the Type enum in Type.hpp (to make the most recent …
=> Infoboxes/Content: add estimated task speed infobox

src/InfoBoxes/Content/Factory.cpp
Make infobox descriptions consistent in hyphenation of "cross-country".
=> InfoBoxes/Content: make infobox descriptions consistent in hyphenation of cross-country

src/InfoBoxes/Content/Type.hpp
Make the latest entries in the Type enum formatted like the earlier entries. This just removes blank lines and adds two comment lines (grouping the entries in tens).
=> InfoBoxes/Content: Type enum cleanup (only whitespace and comments)

doc/manual/en/ch04_xc_tasks.tex, doc/manual/en/ch05_glide_computer.tex, doc/manual/en/ch10_infobox_reference.tex
Add language about new "Speed task estimated" infobox (PR #1429), and correct and clarify some language about task speeds.
=> doc/manual: new infobox and task speed language clarification and correction

NEWS.txt, src/Look/HorizonLook.cpp, src/Look/HorizonLook.hpp, src/Renderer/HorizonRenderer.cpp, src/Renderer/HorizonRenderer.hpp, test/src/RunHorizonRenderer.cpp
more elaborate artificial horizon with standard colorblind-friendly colors, shape and marks
=> Renderer/HorizonRenderer: more elaborate artificial horizon

NEWS.txt, src/Dialogs/StatusPanels/TaskStatusPanel.cpp
This change makes “Speed estimated” on the Task-Status panel blank when “Speed remaining” on that panel is blank. The latter is blank if MC>0 but the task can’t be finished due to either too much wind or MC setting being too low given the amount of wind. Like “Speed remaining”, “Speed estimated” (the predicted start-to-finish average task speed) has no meaning if the task can’t be finished. This also makes this field more like infoboxes that show “---” in this can’t-finish-task scenario (e.g., “V Task Est” and “Fin ETA”).
=> Dialogs/StatusPanels: On the Status-Task panel, make “Speed estimated” blank when “Speed remaining” is blank.

NEWS.txt, src/lua/Http.cpp
Applies the same common Curl options that are used elsewhere in XCSoar for the Lua HTTP client. These currently include disabling host and peer SSL verification on Android to circumvent connection errors due to missing access to Android's own CA certs (#1469)
=> lua/Http.cpp: Use common curl settings

src/Dialogs/Waypoint/dlgWaypointDetails.cpp
Guess this is what is wanted
closes #1443 
I did notice when testing that the panto function could be improved. The infobox pannel is still open when you press panto so you end up in pan mode but with that panel widget still open. 
Or maybe this pannel should close when "details" is pressed.
=> Add pan to

NEWS.txt, src/Dialogs/StatusPanels/TaskStatusPanel.cpp
This change makes “Estimated task time” and “Remaining time” on the Task-Status panel blank when “Speed estimated” and “Speed remaining” on that panel are blank. These speeds are blank if MC>0 but the task can’t be finished due to either too much wind or MC setting being too low given the amount of wind. Like these speeds, “Estimated task time” (the predicted start-to-finish task time) and “Remaining time” (the predicted time required to fly the remainder of the task) have no meaning if the task can’t be finished. This also makes these fields more like infoboxes that show “---” in this can’t-finish-task scenario (e.g., “V Task Est” and “Fin ETA”). The new logical test used to control whether “Estimated task time” and “Remaining time” are shown …
=> Dialogs/StatusPanels: on Task panel, make two times blank when spd rem is blank

build/python/build/libs.py
See note: https://github.com/c-ares/c-ares/releases
=> build/python/libs: fix c-ares download failure

src/Geo/Flat/FlatGeoPoint.hpp, src/Geo/GeoPoint.hpp, src/Math/Point2D.hpp, src/PageSettings.hpp
The declaration of the inequality operator "operator!=" together with the declaration of the "operator==", be it defaulted or not, may be a problem. The reference manual says "per the rules for operator==, this will also allow inequality testing." In other words declaring the equality operator implicitly declares the inequality operator. The reference manual is not explicit what happens if both operators are declared. Hence the excessive declarations of inequality operators should be removed from the code.
Details are here:
https://en.cppreference.com/w/cpp/language/default_comparisons
=> remove inequality operators

doc/manual/en/ch05_glide_computer.tex
Clarifies and cleans up the last four paragraphs of section 6.11 (Task speed estimation).
=> doc/manual: 6.11 (Task speed estimation) clarification and clean-up

src/PageSettings.hpp
This is an add-on to PR #1505 where I had missed out this one inequality operator.
The declaration of the inequality operator "operator!=" together with the declaration of the "operator==", be it defaulted or not, may be a problem. The reference manual says "per the rules for operator==, this will also allow inequality testing." In other words declaring the equality operator implicitly declares the inequality operator. The reference manual is not explicit what happens if both operators are declared. Hence the excessive declaration of inequality operator should be removed from the code.
Details are here:
https://en.cppreference.com/w/cpp/language/default_comparisons
=> remove inequality operator

src/MapWindow/OverlayBitmap.cpp
The old header for libboost multi polygon class is deprecated (boost/geometry/multi/geometries/multi_polygon.hpp) and will be removed in Boost 1.86. The new one is boost/geometry/geometries/multi_polygon.hpp.
=> Boost: Use non-deprecated version of multi_polygon.h

src/Dialogs/Waypoint/Manager.cpp
Change the title from "Waypoints Editor" to "Waypoint Editor" to match the label on the button that takes the user to the waypoint editor dialog and to be more consistent with other similar titles... like "Task Manager" (not "Tasks Manager") and "Waypoint List" (not "Waypoints List").
=> Dialogs/Waypoint: change "Waypoints Editor" to "Waypoint Editor"

doc/lua.rst, src/lua/Task.cpp
Fixes ETA times returned via `next_eta` and `final_eta` variables, now returning number of seconds since midnight of the day of arrival. Previous values did not make sense, at least by my level of understanding of the code.
=> lua/Task: fix returned eta times

NEWS.txt, src/Waypoint/WaypointReaderSeeYou.cpp
(This is a redo of PR #1499, which was closed and inadvertently left out of the v7.43 release.)
This change restores the check for a header (a line containing only field names) in a CUP-format waypoint file when reading the file. This fixes a problem introduced in v7.42 via PR #1305, part of which was the removal of such a check. This (probably inadvertently) made it so that XCSoar now assumes there to always be a header. The XCSoar-created user.cup file, though, historically hasn’t had a header – and currently isn’t given one when XCSoar creates the file. So the changes in PR #1305 made it so that the first record (waypoint) in user.cup is ignored. If a new waypoint is added via the Waypoint Editor’s “New” or “Import” function, the result is worse: the first waypoint in user.cup is …
=> src/Waypoint: restore check for header in user.cup

src/Dialogs/Airspace/AirspaceList.cpp
some minor changes. In the airspace list have the filter option be listed as Unknown since it is Unknown anywhere else in the app (it is other in the code) 
and have AY Unclassified change to unknown as Unclassified is used for AC field makes it better to set the correct colors and filters for the map display this way.
=> More extended airspace fixes

src/Dialogs/Settings/Panels/LoggerConfigPanel.cpp, src/Dialogs/Settings/dlgBasicSettings.cpp
Max. selectable value for crew weight increased to 500 (both in "Flight Setup" and "Logger Setup").
Reason:
The drop-down selection for "Crew Weight" was limited to a value of 300, regardless of unit for mass. 
If the user has selected "lb" as unit, the max. possible crew weight would be 300 lb (=136 kg), which is easily exceeded if both seats are occupied. 
Most gliders are limited to a max. seat weight of 242 lb, so using 500 as max. value should
cover all use cases (2 * 242 lb = 484 lb). I am not aware of a glider with a useful load of more than 500 lbs anyway.
=> Max. selectable value for crew weight increased to 500.

ide/vagrant/Vagrantfile
- Support Windows host for Vagrant explicitely (with RAM and CPU determination)
- Mounts ~/.xcsoar into the VM for Windows, Mac and Linux
=> Vagrantfile: Support Windows explicitely; mount ~/.xcsoar into virtual machine

.gitignore, ide/docker/Dockerfile
With this env variable set, ccache calls from within Docker containers will work seamlessly, sharing a common db on the repo checkout folder
=> Use a shared folder for ccache when running inside Docker

.github/workflows/build-translation.yml
This workflow checks if there are new strings to translate. If so, it provides an update of the translation template 'xcsoar.pot' and the language files *.po in the folder XCSoar/po, which then can be pulled from weblate. New translations are later pushed from weblate into the *.po files in XCSoar/po.
This PR will solve the issues #1602 and #1603.
=> Create build-translation.yml: autocommit of translation sources

AUTHORS, NEWS.txt, android/AndroidManifest.xml, android/testing/AndroidManifest.xml
This PR enables XCSoar to be displayed in front of the Android lockscreen.
The idea of this PR is to remove in-flight distractions during phone unlocking (entering a PIN, drawing a pattern, etc.). Instead, XCSoar is immediately available when powering the phone display. Equally, the lockscreen is easily reached by moving the App to the background (e.g., through an upward gesture or pressing the home button). Note that the feature only applies, if the screen was locked while the App was in foreground.
The PR appends two lines to the Android manifest and, as such, includes the feature by default. In many phones, however, the feature must be manually activated over the system's App settings, as illustrated in the attached screenshot (cf. _Show on Lock screen_).
It must be noted that, in some …
=> Android: Activity in front of lockscreen

build/flags.mk
Building with Apple CLANG 16 (shipped with Xcode 16.0) did not work due to the `-fcoroutines-ts` being deprecated and removed.
=> Fixed build flags for Apple CLANG 16

src/Gauge/ThermalAssistantRenderer.cpp
ThermalAssistant in dark mode is readable again.
=> Gauge/ThermalAssistantRenderer.cpp: Use MixMask on Windows

NEWS.txt, src/Dialogs/Settings/Panels/ScoringConfigPanel.cpp, src/InfoBoxes/Content/Task.cpp, src/MapSettings.cpp, src/MapSettings.hpp, src/Profile/Keys.hpp, src/Profile/MapProfile.cpp
Implementation of feature described in issue #1084 - added comments on two infoboxes as helpers to the AAT target distance being flown, optionally enabled in the profile.
This required refactoring the maximum distance calculation algorithm for re-usability and fixing a minor bug in the distances displayed in the Task Manager ui - see discussion on the issue for more details.
Testing done
-------------
* Added test assertions for the initially calculated min and max distance. Ensured these run ok at every refactor step.
* Added assertions checking min, max & max total distances calculated after flying the task. However these were not committed as test is too heavy to run in the `make check` test suite, and there are few tests presently failing in `make testfast` and `make testslow`. I will …
=> Support for Argentinean 95% distance rule & task maximum distance fix

android/src/BluetoothHelper.java, android/src/BluetoothSensor.java, android/src/BluetoothUuids.java
GATT stuff runs now on the main thread, thus the os does not call close() before connection is fully established. Discovered services and characteristics are fetched from os and handled in xcs code, thus consecutive os calls will not fail.
This will fix long standing bugs for me. Tested on Pixel 6, 9 and Xiaomi Redmi 9S with Android 14, 15 and 13.
=> Android:GATT fix and improvement

NEWS.txt, doc/manual/de/ch07_airspace_and_flarm.tex, doc/manual/en/ch07_airspace_and_flarm.tex, doc/manual/fr/ch07_airspace_and_flarm.tex, src/MainWindow.cpp
Manual updated for en, de and fr. Others pending.
Closes #1641
=>  Make Flarm gauge disappear when traffic is farther than 4 km away

Data/iOS/Info.plist.in.xml, src/lib/curl/Setup.cxx
Allowing http and not verified https downloads for iOS.
=> Allowing http and insecure https downloads on iOS

README.md, doc/build.rst, doc/devsetup.rst
The '--recursive' option works on the 'git submodule' subcommand only. For 'git clone' et al. the proper option is '--recurse-submodules'.
Also, give the reference to the git documentation there where the text goes into 'more information about git'.
=> Doc: Define proper git command options

Data/iOS/Info.plist.in.xml, build/ios.mk, build/targets.mk, src/LocalPath.cpp
Adds an additional build target using the iOS simulator SDK to be able to run the app in the simulator and fixes a missing slash in local paths. Mostly adapted from the work by @piopawlu.
=> iOS simulator and local paths

src/ui/canvas/opengl/FBO.hpp, src/ui/canvas/opengl/FrameBuffer.hpp, src/ui/canvas/opengl/RenderBuffer.hpp, src/ui/window/sdl/TopWindow.cpp
Without the PR, the app effectively gets stuck on the initial loading/progress screen.
As discovered by @piopawlu, this is mostly due to OpenGLES on iOS not having the default framebuffer indexed with 0, making the unbind fail (see e.g., [https://stackoverflow.com/questions/56786676/how-to-unbind-glbindframebuffer-in-c-opengles-ios](https://stackoverflow.com/questions/56786676/how-to-unbind-glbindframebuffer-in-c-opengles-ios)).
=> iOS: Fix resizing and rendering

test/src/TestUTF8.cpp
- Order the test length calculation according to tests
- Identify NextUTF8 test block with comment
- Add additional test on NextUTF8 End-of-String behavior
- Encapsulate UnicodeToUTF8 tests in block also
=> test: Cleanup UTF8 test

NEWS.txt, src/Gauge/FlarmTrafficWindow.cpp, src/Look/FlarmTrafficLook.cpp, src/Look/FlarmTrafficLook.hpp
File:
This commit is based on description and discussion on https://github.com/XCSoar/XCSoar/issues/1643
Within the map FLARM- targets are colour coded. Blue means "above", green means "below" and violet means "same height".
The targets in the radar display (small and big) become now the same colours.
The original colour "blue" in the radar display indicated the selected target (i.e. by tapping on it on the touchscreen). Also the upper left field with the FlarmID or call-sign was displayed within this blue colour. Now this blue colour is no more used.The selected target is visually marked by a bold border line.
The original radar classified the targets into 2 types (passive- with engines) and active (gliders,para-gliders).
The text beside the targets shows height or sink/ascend- rate. It …
=> FLARM Target Colours in Radar Display

doc/build.rst, src/util/Compiler.h
Commit 2c43d6f8 changed policy from clang 10 to clang 12. However, unlike commit 9c968559 and commit 0c061b47, this change was not permeated into other parts of the repository. This commit tries to make things consistent.
With this change we loose building using clang on bullseye (oldstable).
=> Clang: enforce policy for clang 12

doc/build.rst
Links to various libraries used in the build are included, but most are outdated. This commit updates the URLs to present day locations.
=> Doc: Update URLs in build documentation

doc/build.rst, ide/provisioning/install-debian-packages.sh
For the last two Debian releases the libfreetype6-dev package has been a transition package to libfreetype-dev. Replace the transition package with the target package.
=> Debian: replace transition package libfreetype6-dev

Data/icons/scalearrow_left.svg
Previous design created ugly white rectangle with different text sizes during panning and menu buttons activation. Now is zoom value symetricaly surrounded with arrows, which works for all cases.
=> Update scalearrow_left icon with universal arrow

debian/rules
Enhance rules file to pick up the 'parallel' build option and create the make option from it.
=> Debian: allow for parallel build

NEWS.txt, src/Gauge/BigTrafficWidget.cpp, src/Gauge/BigTrafficWidget.hpp, src/Gauge/GaugeFLARM.cpp, src/Gauge/TrafficSettings.cpp, src/Gauge/TrafficSettings.hpp, src/Profile/Keys.hpp, src/Profile/UIProfile.cpp
To save/restore the zoom range over pages and XCSoar restart it was necessary to add a new paramater in the profile. If this paramter is not known in the profile the default 5km is used.
By this enhancement the change between pages becomes more consitent. See the description in
https://github.com/XCSoar/XCSoar/issues/1681
In addition the zoom range on the big radar is set to 5 km when clicking on the small radar on the map. This makes sense because the small radar appears when an object comes into the 4km range. see the following screenshots.
=> Save/Restore FLARM radar zoom on page change

NEWS.txt, build/libcontest.mk, doc/manual/de/ch11_configuration.tex, doc/manual/en/ch11_configuration.tex, doc/manual/fr/ch11_configuration.tex, python/src/Flight/AnalyseFlight.cpp, src/Computer/TraceComputer.cpp, src/Engine/Contest/Solvers/ContestDijkstra.cpp, src/Engine/Contest/Solvers/OLCLeague.cpp, src/Engine/Contest/Solvers/OLCSprint.cpp, test/src/AnalyseFlight.cpp, test/src/RunContestAnalysis.cpp
Partially fixes #569 - a customizable sprint time would be preferable, but is currently not needed as the two sprint contests known to me both have a 2 hour window now.
=> Sprint time update

src/NMEA/ExternalSettings.cpp, test/src/TestDriver.cpp
#1703 introduced a bug in the transponder code and mode settings by accidentally deleting lines during a force-push.
=> Fix transponder code

NEWS.txt, build/main.mk, src/Device/Driver/FLARM/Device.hpp, src/Device/Driver/FLARM/Settings.cpp, src/Device/Driver/FLARM/StaticParser.cpp, src/Device/Port/TTYPort.cpp, src/Dialogs/Device/DeviceEditWidget.cpp, src/Dialogs/Device/DeviceListDialog.cpp, src/Dialogs/Device/FLARM/ConfigWidget.cpp, src/Dialogs/Device/FLARM/ConfigWidget.hpp, src/Dialogs/Device/FLARM/RangeConfigWidget.cpp, src/Dialogs/Device/FLARM/RangeConfigWidget.hpp, src/Dialogs/Device/ManageFlarmDialog.cpp, src/Dialogs/Device/ManageFlarmDialog.hpp, src/FLARM/Data.hpp, src/FLARM/Hardware.hpp
This is how I would do the hardware read-out and optional config items based on it, but I'm not sure, if it is the best way. I think there are more possibilities to make stuff re-usable and more maintainable. 
Code is tested and based on official FLARM interface documents.
Ref: #1647
=> FLARM hardware read-out and additional config options

src/Device/Driver/FLARM/Parser.cpp, src/Dialogs/Device/ManageFlarmDialog.cpp, src/FLARM/Hardware.hpp
Small amendment to #1715.
@lordfolken can you check with a classic FLARM device? Also, using line.Rest() is a bigger change which puts more responsibility to the caller. Haven't found a regression for existing implementations though.
=> Show Flarm ID in config dialog

src/Look/MapLook.cpp, src/Renderer/TrackLineRenderer.cpp
With 7.44 (unsure if other versions) the track line on high resolution android devices is very small. It seems to be scaled down and is the same 3 pixels wide and 400 pixels long but that makes it super tiny on android devices such that its very short and barely visible due to being 3 pixels wide.
This fixes it making it scale with the resolution so it looks the same as it does on other platforms.
Tested on LG G7 thinQ at 1440 x 3120 pixels (picture from same android device)
=> fix track line scaling on high res android devices

src/Device/Util/NMEAReader.cpp, src/NMEA/Checksum.cpp, src/NMEA/Checksum.hpp, test/src/AddChecksum.cpp
See https://github.com/XCSoar/XCSoar/issues/1365.
=> Revert "NMEAChecksum: initializer list is ambigous on OSx"

src/Device/Driver/LX/NanoLogger.cpp
XCSoar Version 7.44
Issue #1765
This change will list the nano logger flights in date descending order, newest first and oldest last.
This will make the latest flight to download the default, rather then having to scroll to the bottom of the list to select it.
=> List nano downloadable flights in reverse order

src/Engine/Task/Factory/TaskFactoryType.hpp
Some weglide competitions allow maximum points for a declared task that finishes within 1000 meters below the start height.
This change will facilitate that requirement.
=> Allow racing tasks to use the FAI finish height rules for final glide calculations

src/Airspace/AirspaceVisibility.cpp, src/Airspace/AirspaceVisibility.hpp, src/CrossSection/AirspaceXSRenderer.cpp
With the extended openair format airspace have at class and type We need to check both of these to know weather or not to draw the airspace
Renamed the boolean to reflect that it now checks both.
closes #1746
=> Airspace/AirspaceVisibilty.cpp: Also check type

build/android.mk, build/imagemagick.mk, build/ios.mk, build/resource.mk
ImageMagick v7 is default on macOS/homebrew but currently not available via apt on Linux; hence, on macOS, we saw a lot of `WARNING: The convert command is deprecated in IMv7, use "magick"` during compilation...
This solution now checks if ImageMagick v7 is available (by checking if the `magick` command is available); if not, it falls back to the IMv6 commands. This was suggested in the discussion of https://github.com/XCSoar/XCSoar/pull/1536 for best compatibility.
=> build/{imagemagick,resource,android,ios}.mk: Support ImageMagick v7

src/Engine/Task/Factory/AATTaskFactory.cpp
This change makes the "Arm start manually" default consistent across all task types.
=> Set AAT task type "Arm start manually" default to "Off"

NEWS.txt, src/InfoBoxes/Content/Factory.cpp, src/InfoBoxes/Content/Task.cpp, src/InfoBoxes/Content/Task.hpp, src/InfoBoxes/Content/Type.hpp
The new infobox will show your average task speed for the current leg of a racing task.
=> Add new infobox speed task leg.
