.circleci/config.yml
Addresses https://github.com/XCSoar/XCSoar/pull/50#issuecomment-337133766
=> Add basic CircleCI instructions

.gitmodules
=> Adjust URL for `android/ioio` submodule

build/flags.mk, python/src/Airspaces.cpp, python/src/Flight.cpp, python/src/PythonConverters.cpp, python/src/PythonGlue.cpp, python/src/PythonGlue.hpp, python/src/Util.cpp
see https://github.com/skylines-project/py-xcsoar/issues/15
/cc @roeles @TobiasLohner
=> Add Python 3 compatibility

AUTHORS, src/Dialogs/Settings/Panels/SafetyFactorsConfigPanel.cpp
As a result of a recent post on the XCSoar Forum.
See [post](https://forum.xcsoar.org/viewtopic.php?f=2&t=3255)
=> Allow "Arrival Height" above 1000 ft

src/LocalPath.hpp
Fix a divergence of the documentation of ::LocalPath(Path) from its
signature.
=> LocalPath: Updated documentation

src/Device/Driver/AirControlDisplay.cpp
Added volume control and setting of passive (secondary) frequency as per device capabilities
=> ACD driver update for radio control

.gitlab-ci.yml, ide/docker/Dockerfile, ide/docker/README.md, ide/docker/bin/xcsoar-compile, ide/docker/bin/xcsoar-test, ide/provisioning/install-debian-packages.sh
This PR is depends on #240.
todo:
edit:
20190815: fixed ToDos.
=> Add gitlab-CI

doc/manual/en/input_events.tex
https://github.com/XCSoar/XCSoar/issues/238
=> doc: custom input files menu location amended

doc/manual/fr/ch01_introduction.tex
Translation of the introduction chapter based on current English version
=> Doc: French: Full update of the introduction chapter

src/Device/Driver/OpenVario.cpp
- Add voltage reporting from hardware
- Send MacCready back to vario logic
- Send Bugs and Balast back to vario logic
- Send glider polar back to vario logic
=> Driver Openvario: More protocol commands integrated

doc/manual/xcsoar.sty
- Removal of space character after names, to avoid extra space in text
- Removal of mbox around url to allow for proper line break
=> Doc: Sty: small changes

doc/manual/en/XCSoar-in-a-flash.tex
=> Doc: En: quick guide: URL update

doc/manual/fr/XCSoar-Prise-en-main.tex
A new version of the French quick startup guide based on the current English version
=> Doc: FR: Quick guide: general update based on EN version

doc/manual/fr/installation.tex
Translation of the installation chapter based on current english version
=> Doc: French: Full update of the installation chapter

doc/manual/en/installation.tex
Correction of a few glitches and update of some piece of information
=> Doc: English: Correction of a few details

doc/manual/fr/ch03_navigation.tex
This is a major update of the French chapter "Navigation" based on the (slightly updated) English version.
=> Manual: FR: Navigation: Full translation

doc/manual/en/ch03_navigation.tex
This is a small update of the Navigation chapter (in English), specifically:
- syntax
- clarification between altitude and height
- a few additional explanations
=> Manual: EN: Navigation: small update

AUTHORS, NEWS.txt, build/main.mk, doc/manual/en/ch10_infobox_reference.tex, src/ActionInterface.cpp, src/ActionInterface.hpp, src/InfoBoxes/Content/Factory.cpp, src/InfoBoxes/Content/Radio.cpp, src/InfoBoxes/Panel/RadioEdit.cpp, src/InfoBoxes/Panel/RadioEdit.hpp
This branch modifies the existing radio infoboxes, and expands them with the option to manually modify the radio frequency that the infobox shows.
=> Radio frequency infobox panel

doc/manual/en/ch06_atmosphere_and_instruments.tex
Small improvements (typo, etc.)
=> Doc: En: chap6 atmos & stat: small improvements

doc/manual/fr/ch06_atmosphere_and_instruments.tex
Chap 6 was not translated into French.
First version is here.
=> Doc: Fr: chap 6 atmos & instruments: initial translation

doc/manual/fr/ch05_glide_computer.tex
Major update of the French translation of chapter 5 (Glide computer), based on new English version (PR #312).
=>  Doc: FR: Update of chapter 5 glide computer

doc/manual/en/ch05_glide_computer.tex
Checking the manual against XCSoar-testing 7.0_preview14.
Removing some information and adding some others.
Plus some syntax improvements.
=> Chapter 5 glide comput: Update based on XCSoar-testing

doc/manual/fr/ch04_xc_tasks.tex
Major update of the French translation of chapter 4 (Cross-country tasks), based on new English version (PR #309).
=> Doc : FR : Update of chapter 4 xc tasks

doc/manual/en/ch04_xc_tasks.tex
Checking the manual against XCSoar-testing 7.0_preview14.
Removing some information and adding some others.
Plus some syntax improvements.
=> Chapter 4 xc tasks: Update based on XCSoar-testing

doc/manual/en/ch01_introduction.tex
Update of the status of current platforms able to run XCSoar, and of the links to XCSoar resources.
(same content as PR #265, but in a single commit)
=>  Manual: En: Introduction: Update: Platforms, etc.

src/Device/Driver/KRT2.cpp
=> Driver/KRT2: respond to remote query from radio

doc/manual/fr/ch08_avionics_and_airframe.tex
First translation from English to French of this chapter.
=> Doc: FR: Chap 8 Airframe & Avionics: initial version

doc/manual/fr/ch07_airspace_and_flarm.tex
Improvements of the French version of chapter 7 based on English version.
Vocabulary homogenization. Rewording.
=> Doc: FR: Chap7: Improvements based on EN version

src/ApplyExternalSettings.cpp, src/Device/Driver/KRT2.cpp, src/NMEA/ExternalSettings.cpp, src/NMEA/ExternalSettings.hpp
=> Fix mechanism to communicate frequency changes made on KRT2.

doc/manual/en/ch07_airspace_and_flarm.tex
A few minor improvements and spelling corrections
=> Doc: En: Chap7: spelling and minor improvements

doc/manual/en/ch12_data_files.tex
=> DOC: Empty elevation field

NEWS.txt, src/Device/Declaration.cpp, src/Device/Declaration.hpp, src/Device/Driver/LX/Convert.cpp, src/Device/Driver/LX/LXN.hpp, src/Device/Driver/LX/NanoDeclare.cpp, src/Dialogs/Settings/Panels/LoggerConfigPanel.cpp, src/IGC/IGCWriter.cpp, src/IGC/IGCWriter.hpp, src/Logger/LoggerImpl.cpp, src/Logger/Settings.cpp, src/Logger/Settings.hpp, src/Profile/ComputerProfile.cpp, src/Profile/ProfileKeys.cpp, src/Profile/ProfileKeys.hpp, test/src/RunIGCWriter.cpp, test/src/TestLogger.cpp
next try, hope my pull request is now in a better shape.
=> Added the CoPilot to the logger Settings

src/Tracking/SkyLines/Glue.cpp
moved from `40.113.110.147` to `212.51.149.149`
=> update skylines tracking server IP #404

src/Dialogs/FileManager.cpp, src/Repository/AvailableFile.hpp, src/Repository/Parser.cpp
- Show "Update available" if files are out of date
- Add "Update All" button that downloads all updates
=> Show if files are out of date in file manager

ide/docker/README.md, ide/docker/bin/xcsoar-compile, ide/provisioning/install-debian-packages.sh
=> Docker compile script update, running xcsoar from docker

build/python/build/libs.py
=> build/python/libs: update OpenSSL to 3.0.0-alpha3

ide/docker/Dockerfile, ide/docker/bin/xcsoar-compile, ide/docker/bin/xcsoar-test
Improve Dockerfile
Allow scripts to accept arguments i.e.: 
```bash
xcsoar-compile UNIX everything V=2 USE_CCACHE=y DEBUG=n
```
=> Dockerimprove

src/Tracking/SkyLines/Glue.cpp
We need to update the tracking ip address of the server for skylines. Its now 212.51.149.212
=> Tracking/Skylines: Update Server IP

src/Weather/Rasp/Providers.cpp
RASP Poland source added from https://fcst.pl/ 
There are 7 weather calculations : 
current day 2.4km
day+1 4km
day+2 4km
day+3 4km
day+4 4km
day+5 4km
day+6 4km
No related issue
=> Update Providers.cpp for RASP Poland

NEWS.txt, src/PageActions.cpp, src/PageState.hpp
----------------------------------------
This is an extension to the distinct page zoom. With this you can have multiple map windows and enable auto zoom per window.
=> PageActions: manage auto zoom state per page

.github/workflows/build-container.yml
Docker Build environment uploaded to ghcr.io packages. 
Rebuilt when there are changes under ./ide/provisioning or ./ide/docker/
=> automatically build and push docker build env

.github/workflows/build-container.yml, .github/workflows/build-unix.yml
=> Dockerbuildenv

NEWS.txt, build/libcontest.mk, src/Dialogs/Settings/Panels/ScoringConfigPanel.cpp, src/Engine/Contest/ContestManager.cpp, src/Engine/Contest/ContestManager.hpp, src/Engine/Contest/ContestStatistics.hpp, src/Engine/Contest/Solvers/WeglideDistance.cpp, src/Engine/Contest/Solvers/WeglideDistance.hpp, src/Engine/Contest/Solvers/WeglideFAI.cpp, src/Engine/Contest/Solvers/WeglideFAI.hpp, src/Engine/Contest/Solvers/WeglideFree.cpp, src/Engine/Contest/Solvers/WeglideFree.hpp, src/Engine/Contest/Solvers/WeglideOR.cpp, src/Engine/Contest/Solvers/WeglideOR.hpp, src/Renderer/FlightStatisticsRenderer.cpp, test/src/RunOLCAnalysis.cpp
Weglide contest solvers added.
loosely related: #569
=> Engine/Contest/Solvers/Weglide*: WeGlide contests

.github/workflows/build-unix.yml
Invert the match, so all other changes trigger a compile.
=> gh-workflow: invert path match

doc/manual/de/XCSoar-Blitzeinstieg.tex, doc/manual/en/supported_devices_table.tex
=> Manual fix & XCVario addition.

AUTHORS, NEWS.txt, src/Polar/PolarStore.cpp
Adds Wassmer WA 26 P Squale polar
update news and contributor files
=> Squale polar

src/Device/AndroidSensors.cpp
I want to get started with BLE since this is new in 7.11
The intend is to learn from the experiment. Any comment is highly appreciated!
The code changes may not make it into the production code.
At this time the codes does not behave as intended. See commit message for more detail.
=> read barometric pressure from an experimantal BLE peripheral.

android/src/BluetoothSensor.java
Full document:
https://github.com/flytec/SensBoxLib_iOS/blob/master/_SensBox%20Documentation/SensorBox%20BLE%20Protocol.pdf
=> Fix for SensBox BLE vario and GNSS altitude values

ide/vagrant/Vagrantfile
<!--
Please link any relevant issues or forum posts here, for reference.
If this PR resolves an existing issue, please write "Closes #1234" so that
the issue is closed automatically when
=> ide/vagrant: update to bullseye

src/Dialogs/dlgAnalysis.cpp
Fix typo in Task (c)Calc button name to make all instances uniform
=> Fix typo in Task Calc button description/dlgAnalysis.cpp

src/Device/Driver/XCVario.cpp
Brief summary of the changes:
add PutQNH() method to XCVario device driver in order to sync QNH value set in XCS to the device.
Related issues and discussions:
Meanwhile MC, Ballast and Bugs were supported from inherited CAI302 commands since begin, here comes the missing part for QNH sync with a new implementation in recent XCVario code:
https://github.com/iltis42/XCVario/commit/86b99b0a15636247bd31b195a081ffad75a216a6
=> Extend driver to sync also QNH to XCVario device

doc/manual/de/XCSoar-Blitzeinstieg.tex, doc/manual/de/ch01_introduction.tex, doc/manual/de/ch05_glide_computer.tex, doc/manual/de/ch07_airspace_and_flarm.tex, doc/manual/de/ch11_configuration.tex, doc/manual/de/ch12_data_files.tex, doc/manual/de/ch13_history.tex, doc/manual/en/XCSoar-in-a-flash.tex, doc/manual/en/ch01_introduction.tex, doc/manual/en/ch05_glide_computer.tex, doc/manual/en/ch11_configuration.tex, doc/manual/en/ch12_data_files.tex, doc/manual/en/ch13_history.tex, doc/manual/en/installation.tex, doc/manual/en/integration.tex, doc/manual/fr/ch05_glide_computer.tex, doc/manual/fr/ch11_configuration.tex, doc/manual/fr/ch12_data_files.tex, doc/manual/fr/installation.tex, doc/manual/pt_BR/XCSoar-in-a-flash-pt_BR.tex, doc/manual/pt_BR/ch05_glide_computer.tex, doc/manual/pt_BR/ch11_configuration.tex, doc/manual/pt_BR/ch12_data_files.tex, doc/manual/pt_BR/ch13_history.tex, doc/manual/pt_BR/installation.tex, doc/manual/pt_BR/integration.tex, doc/manual/xcsoar.sty
Openair Radio Frequency 'AR' or 'AF' (Additional OpenAir fields here - http://www.winpilot.com/UsersGuide/UserAirspace.asp)
=> Doc openair format harmonization 'AR' or 'AF'

NEWS.txt, android/AndroidManifest.xml, android/src/XCSoar.java
Closes #618
Here's the video for Google Play Store: https://www.youtube.com/watch?v=h14BWgzDD0w
=> Android background location prominent disclosure dialog

python/src/PythonConverters.cpp, python/src/PythonConverters.hpp, python/test/test_xcsoar.py
Fixed a crash in the python modules flight.path() method that I recently found when trying it out. Also made the python tests run with python 3.
No related issues or discussions found. Seems not many people are using the python module.
=> Fix crash in python module's flight.path()

src/Waypoint/CupWriter.cpp
=> cupwriter: add missing comma for shortname

tools/polar_import.py
Proper command line handling. 
Fix legend colors.
=> Fix some glitches on polar_import script.

src/Dialogs/dlgCredits.cpp
=> dlgCredits: relayout credits dialog, include logo

README.md, doc/build.rst, doc/devsetup.rst
=> doc: change github urls to https due to gh policy change

NEWS.txt, build/libcontest.mk, src/Dialogs/Settings/Panels/ScoringConfigPanel.cpp, src/Engine/Contest/ContestManager.cpp, src/Engine/Contest/ContestManager.hpp, src/Engine/Contest/Settings.hpp, src/Engine/Contest/Solvers/Charron.cpp, src/Engine/Contest/Solvers/Charron.hpp, src/Engine/Contest/Solvers/ContestDijkstra.cpp, src/Engine/Contest/Solvers/ContestDijkstra.hpp, src/Engine/Contest/Solvers/Contests.cpp, src/Renderer/FlightStatisticsRenderer.cpp, test/src/RunContestAnalysis.cpp
Adds the Charron contest based on the rules at:
https://www.lvzc.be/index.php/secretariaat-2/downloads/charron-line/2013-reglement-charronbeker-2022/file
[Charron](https://www.lvzc.be/charronline/2022/overzicht.php) is an online contest from LVZC. The rules are:
* Maximum 5 legs under 200km, 6 legs above.
* Minimum 20km legs.
* 4 points per km with handicap.
None
=> Engine/Contest/Solvers: Charron contest

doc/manual/en/contributors_dev.tex, doc/manual/en/contributors_doc.tex, doc/manual/en/contributors_other.tex, doc/manual/en/contributors_transl.tex
Items from the AUTHORS file in the root directory of the source distribution
and items from the User Manual merged into the User Manual.
Update of contributors in the User Manual.
=> Manual: Merged contributors into User Manual

src/Form/Form.cpp
=> Windows: Fix Assert in WndForm

doc/XCSoar.doxyfile
=> Documentation: Updated doxygen version.

src/Look/OverlayLook.cpp, src/Look/OverlayLook.hpp, src/MapWindow/GlueMapWindowOverlays.cpp
Cross hair in PAN mode that scales according to the DPI and is visible in both dark and light backgrounds.
partially implements: https://github.com/XCSoar/XCSoar/issues/426
=> Pancrosshair2

NEWS.txt, android/src/UsbSerialHelper.java
=> add U-BLOX 7 USB GPS into 'white list' of USB devices

android/src/UsbSerialHelper.java
=> Adjust naming convention for multiple port UsbSerial devices

Data/Input/default.xci, src/Blackboard/BlackboardListener.cpp, src/Device/Driver/AltairPro.cpp, src/Device/Driver/BorgeltB50.cpp, src/Device/Driver/CAI302/Declare.cpp, src/Device/Driver/CAI302/Parser.cpp, src/Device/Driver/CAI302/Settings.cpp, src/Device/Driver/Condor.cpp, src/Device/Driver/EW.cpp, src/Device/Driver/FLARM/Declare.cpp, src/Device/Driver/IMI/Protocol/Conversion.cpp
=> code cleanup

NEWS.txt, src/Dialogs/FileManager.cpp, src/Repository/AvailableFile.hpp, src/Repository/Parser.cpp
=> FileManager: Show repository file date and optional description string

NEWS.txt, kobo/rcS, src/Hardware/DisplayDPI.cpp, src/Hardware/RotateDisplay.cpp, src/Kobo/Kernel.cpp, src/Kobo/Model.cpp, src/Kobo/Model.hpp, src/Kobo/System.cpp, src/Kobo/SystemDialog.cpp, src/ui/canvas/fb/TopCanvas.cpp, src/ui/event/shared/RotatePointer.hpp
The device has similar hardware as Kobo Clara HD.
Closes #882
=> Add support for Kobo Libra H2O

NEWS.txt, src/Dialogs/Settings/Panels/SymbolsConfigPanel.cpp, src/Look/TrailLook.cpp, src/MapSettings.hpp, src/Renderer/TrailRenderer.cpp
Add an E-ink friendly trail type
https://github.com/XCSoar/XCSoar/issues/216#issuecomment-1445405961
=> Add an E-ink friendly trail type

src/Device/Driver/FLARM/Declare.cpp
=> Device/Driver/Flarm/Declare: indent with spaces

src/Dialogs/Plane/PlaneDetailsDialog.cpp
Copy one more item from the polar list selection.
Closes #1132
=> Plane details, take over handicap factor from list selection. 

doc/manual/de/ch03_navigation.tex, doc/manual/de/ch13_history.tex
Some spelling issues in the documentation
=> Docu: spelling failures and similar

NEWS.txt, src/Device/Driver/ATR833.cpp
Extended driver to read-out and use data delivered by ATR833.
prerequisite to #594
=> Device/Driver/ATR833: use data delivered by ATR833

build/freetype.mk, build/pkgconfig.mk
This PR has 2 commits:
1. Verify that FreeType version meets minimum requirement
2. In the example, enclose version comparators in quotes
#1173
=> Verify FreeType version meets minimum requirement

NEWS.txt, build/test.mk, src/Device/Driver/AirControlDisplay.cpp, src/Dialogs/Device/DeviceListDialog.cpp, src/InfoBoxes/Content/Factory.cpp, src/InfoBoxes/Content/Radio.cpp, src/InfoBoxes/Content/Radio.hpp, src/InfoBoxes/Content/Type.hpp, test/src/TestDriver.cpp
- TransponderSquawk: added for storing transponder code
- Update transponder squawk through ActionInterface
- Device/Driver/AirControlDisplay: send and receive of transponder squawk
- Introduce InfoBoxes for transponder squawk
- Dialogs/Device/DeviceListDialog: show if transponder is available
#867
https://forum.xcsoar.org/viewtopic.php?f=30&t=3424&start=75
=> Transponder squawk class, readout and setting for devices

src/ActionInterface.cpp, src/Device/Descriptor.cpp, src/Dialogs/Settings/Panels/WeGlideConfigPanel.cpp, src/InfoBoxes/Content/Radio.cpp, src/RadioFrequency.hpp
Various code improvements based on lessons learnt from #1167 and #1149.
=> Various code improvements

android/src/NativeSensorListener.java, android/src/SensorListener.java, src/Android/NativeSensorListener.cpp, src/Device/AndroidSensors.cpp, src/Device/Descriptor.hpp, src/Device/SensorListener.hpp
Add device implementation and java bindings for EngineState
https://github.com/XCSoar/XCSoar/issues/1178
https://github.com/XCSoar/XCSoar/commit/52d32fb6913c9e0300a583168383af0d6ca135f9
https://github.com/XCSoar/XCSoar/commit/3b4bbc009adf288fce5484c763ce591bb4cfe9c1
=> Add device and java bindings for EngineState

NEWS.txt, src/Renderer/HorizonRenderer.cpp
- Fixed roll clipping which meant that banks of > 90 degrees were not shown
- Fixed pitch visual issues which resulted in ground being show when pitched up greater than 50 degrees
Before:
https://github.com/XCSoar/XCSoar/assets/6553343/d8b0188f-1a4e-4899-ac22-6733523f54ec
After:
https://github.com/XCSoar/XCSoar/assets/6553343/cdefbf86-3cd4-4e2c-9298-2392f741dea1
- Removed bank angle clamp as this was restricting the visualisation of rolls greater than 90 degrees
- Changed to conditionally drawing ground and sky circle segments.
The reason to remove both the sky and the ground for their respective conditions is that the same issue is present for the sky when pitched down by > 50 degrees - this issue is masked because the ground …
=> Fixed horizon issues for roll clipping and showing only ground when pitched up at 50 Degrees

.github/ISSUE_TEMPLATE/Bug.md
First describe what you did, then describe what you see and what you expected to see.
Add a prompt for system information to aid troubleshooting.
=> Bug.md - Move 'Steps to reproduce' before behavior; add System info

build/test.mk, test/src/TestTaskSave.cpp
=> test/TestTaskSave: add a test for saving and loading a task

src/Kobo/WPASupplicant.cpp
=> Fix WiFi not working on Kobo

.github/workflows/build-native.yml, .readthedocs.yaml
=> Readthedocs

.readthedocs.yaml
=> .readthedocs.yaml: add python to tool list

.github/workflows/build-native.yml, src/Gauge/BigTrafficWidget.cpp, src/Gauge/FlarmTrafficWindow.cpp, src/Renderer/RadarRenderer.cpp
=> Flarmrange

src/Dialogs/Airspace/AirspaceList.cpp
=> Dialogs/AirspaceList: Add missing Filter items, add assert to ensure

src/Dialogs/Settings/dlgConfigInfoboxes.cpp
=> Make copy and past of infobox set more clear in UI

src/Dialogs/dlgCredits.cpp
=> Typo fix in Credits dialog

.clang-format, NEWS.txt, src/Engine/Route/RouteLink.cpp, src/Engine/Route/RouteLink.hpp
=> Smallfixmay24

src/Dialogs/Waypoint/WaypointCommandsWidget.cpp, src/Dialogs/Waypoint/WaypointCommandsWidget.hpp
Did all these buttons in one commit because as far as my understanding goes i had to use enum Buttons {...}
So needed fixed number of buttons i assume. 
Either way those if statements to not add the buttons seemed to be the wrong way of doing it.
=> Waypoint/WaypointCommandsWidget.cpp: Dissable frequency buttons

src/Dialogs/Airspace/dlgAirspaceWarnings.cpp, src/Dialogs/Task/Manager/TaskClosePanel.cpp, src/Dialogs/Task/TaskPointDialog.cpp, src/Dialogs/Weather/NOAADetails.cpp, src/Widget/KeyboardWidget.cpp
=> More button fixes

.github/workflows/build-native.yml
this will enable uploads to download.xcsoar.org/testing/
=> github/actions:build-native: correct testing upload reference

src/CrossSection/AirspaceXSRenderer.cpp, src/Dialogs/Airspace/AirspaceList.cpp, src/Engine/Airspace/AbstractAirspace.hpp, src/Engine/Airspace/AirspaceSorter.cpp, src/Renderer/AirspacePreviewRenderer.cpp, src/Renderer/AirspaceRendererGL.cpp
This PR fixes issue #1482 and possibly others; further testing is required.
=> Fix issue #1482

build/python/build/libs.py, src/event/net/cares/Channel.cxx, src/event/net/cares/Channel.hxx, src/event/net/cares/CoLookup.cxx, src/event/net/cares/CoLookup.hxx, src/event/net/cares/Error.cxx, src/event/net/cares/Error.hxx, src/event/net/cares/Handler.hxx, src/event/net/cares/Init.cxx, src/event/net/cares/Init.hxx, src/event/net/cares/SimpleResolver.cxx, src/event/net/cares/SimpleResolver.hxx
=> 3rdpartyupdate

src/Look/ThermalAssistantLook.cpp
Prevents white plane on white background
Closes #1526
=> src/Look/ThermalAssistantLook.cpp: Always black plane icon

NEWS.txt, PRIVACY.md, src/Tracking/SkyLines/Glue.cpp
=> tracking/xcsoar-cloud: change domain to cloud.xcsoar.org

NEWS.txt, src/Waypoint/WaypointReaderSeeYou.cpp
https://xcsoar.readthedocs.io/en/latest/index.htm
closes #1539
=> WaypointReaderSeeYou: correct PGLanding type to type 21

.clang-format, src/Android/Main.cpp, src/Input/InputEvents.cpp, src/Input/InputEventsActions.cpp, src/XCSoar.cpp
=> Septemberfixes

NEWS.txt, src/Dialogs/Settings/Panels/LayoutConfigPanel.cpp, src/InfoBoxes/InfoBoxSettings.hpp, src/Look/InfoBoxLook.cpp, src/Look/InfoBoxLook.hpp, src/Look/Look.cpp, src/Look/Look.hpp, src/MainWindow.cpp, src/Profile/InfoBoxConfig.cpp, src/Profile/Keys.hpp
This PR implements a solution to Issue #1577
=> scale InfoBox title and comment font

AUTHORS, NEWS.txt, src/MainWindow.cpp
=> MainWindow.cpp: Improved code for flarm radar positions

src/MainWindow.cpp
=> MainWindow.cpp: Adapt size of flarm radar and thermal assistant

src/Look/InfoBoxLook.cpp
=>  InfoBoxLook: reduce title AutoFont calculation to 11 positions

AUTHORS, src/Dialogs/Settings/Panels/LayoutConfigPanel.cpp
=> Titlefontsize

.github/workflows/build-native.yml, NEWS.txt, src/Computer/Settings.cpp, src/Computer/Settings.hpp, src/InfoBoxes/Content/Factory.cpp, src/InfoBoxes/Content/Places.cpp, src/InfoBoxes/Content/Places.hpp, src/InfoBoxes/Content/Type.hpp, src/Renderer/TaskLegRenderer.cpp, src/Waypoint/HomeGlue.cpp
=> Smallfixoct2024

NEWS.txt, android/res/xml/usb_device_filter.xml, android/src/UsbSerialHelper.java
add one more USB VID/PID pair for SoftRF Academy into (Android) 'white list' of USB devices
=> update 'white list' of USB devices with one more VID/PID pair for SoftRF Academy

.github/CODEOWNERS, .github/workflows/build-translation.yml
=> Translationpr

.github/workflows/build-translation.yml
=> build-translation.yml: add branch name

doc/manual/en/ch01_introduction.tex, doc/manual/en/installation.tex
=> doc/manual: update android version

src/Dialogs/Task/dlgTaskHelpers.cpp, src/Engine/Task/AbstractTask.cpp, src/Engine/Task/AbstractTask.hpp, src/Engine/Task/Ordered/OrderedTask.cpp, src/Engine/Task/Ordered/OrderedTask.hpp, src/Engine/Task/Points/SampledTaskPoint.hpp, src/Engine/Task/Points/TaskLeg.cpp, src/Engine/Task/Points/TaskLeg.hpp, src/Engine/Task/Stats/TaskStats.hpp, src/Engine/Task/Unordered/UnorderedTask.cpp, src/Engine/Task/Unordered/UnorderedTask.hpp, test/src/harness_task.cpp, test/src/test_task.cpp
=> 95prefactor

.github/workflows/build-native.yml, build/libboost.mk, build/targets.mk, lib/boost/patches/geometry_no_backward_compatibility, lib/boost/patches/geometry_std_array, lib/boost/patches/geometry_std_math, lib/boost/patches/json_no_hash, lib/boost/patches/no_iostream, lib/boost/patches/no_math_throw, lib/boost/patches/no_multiprecision, lib/boost/patches/variant_no_type
=> Update Boost to 1.87.0

src/Gauge/FlarmTrafficWindow.cpp, src/Renderer/TextInBox.cpp, src/Renderer/TextInBox.hpp
ction to render shadowed text.
Closes #1642
=> src/Gauge/FlarmTrafficWindow.cpp: Use build in fun

build/libcontest.mk, build/libtask.mk, build/main.mk, build/python.mk, build/test.mk
Fix inconsistencies in
- Line continuation
- Indentation
=> Make: clean up makefiles

NEWS.txt, src/MainWindow.cpp, src/PopupMessage.cpp, src/UISettings.cpp
=> PopupMessage: Move to center of Main Area

debian/changelog
- Fix signoff of current release
- Add stub signoff for development version
=> Debian: create valid changelog file

NEWS.txt, android/src/BatteryReceiver.java, src/BatteryTimer.cpp
=> ANDROID: check for valid battery values, use scale factor

src/Profile/InfoBoxConfig.cpp
=> Fix issue 1669. Consitent check for dialog and startup.

NEWS.txt, src/ApplyExternalSettings.cpp
=> ApplyExtrnalSettings: Switch to manual MC when set via external Device

build/main.mk, src/Dialogs/Settings/Panels/LayoutConfigPanel.cpp, src/MainWindow.cpp, src/MainWindow.hpp, src/Menu/ShowButton.cpp, src/Menu/ShowButton.hpp, src/Profile/Keys.hpp, src/Profile/UIProfile.cpp, src/UISettings.cpp, src/UISettings.hpp
For "M" menu button, use the code for Kobo, move it to bottom right, above the status icon.
For zoom in/out buttons, locate them on bottom left, above map scale. They may overlap GPS status icon and text. Thinner frame rectangle as tophat.
Demonstration video: https://www.youtube.com/watch?v=RfnM_tPuCHg
=> Add "M" menu, zoom in/out buttons as Tophat

src/Menu/ShowButton.cpp
Fix the bug which is reported by Sundown3867 in https://github.com/XCSoar/XCSoar/pull/1687.
=> [tophat_flabor] "M" appears only on map screen, e.g. not in the Thermal Assistant screen.

NEWS.txt, src/InfoBoxes/Content/Factory.cpp, src/InfoBoxes/Content/Speed.cpp
resolves #1439
My attempt for the proposed enhancement. The best visual representation (arrows, text) has yet to be agreed upon. Please comment.
=> InfoBoxes/Content/Speed: Add headwind component to V GND Infobox

src/Dialogs/Traffic/FlarmTrafficDetails.cpp, src/FLARM/NameDatabase.cpp, src/FLARM/NameDatabase.hpp
=> Improvements for flarm details dialog

Data/Input/default.xci, NEWS.txt
This opens file picker to select igc file to upload to weglide
=> default.xci: add Weglide button

src/ui/event/sdl/Queue.cpp
I changed the following things in UI::EventQueue::Wait for SDL. This might be a little drastic, hear me out:
-  Moved `FlushClockCaches();` out of the infinite loop to the top of the function.
This is similar to src/ui/event/windows/Queue.cpp and src/ui/android/windows/Queue.cpp and should suffice in my opinion. Maybe I'm missing a case in which it is really necessary to do the reset inside the infinite loop, but I can't think of one right now? Putting the `FlushClockCaches();` before the loop already fixes the issue with timers not firing on iOS, see https://github.com/XCSoar/XCSoar/issues/1697 (and the terrain loading progress bar mentioned in https://github.com/XCSoar/XCSoar/issues/1696, download progress bars are an unrelated issue apparently).
- Removed the `::SDL_PumpEvents()` call. …
=> SDL UI::EventQueue::Wait Better performance and iOS compatibility

NEWS.txt, src/Dialogs/Settings/Panels/GaugesConfigPanel.cpp, src/MainWindow.cpp, src/UISettings.hpp
=> Airspace warning hidden by thermal assistant
